function priors = make_v75_literature_priors()
%MAKE_V75_LITERATURE_PRIORS Literature priors and boundaries for v7.5.
%
% v7.5 treats literature as a set of constrained priors and competing
% hypotheses, not as replacement experimental data.  Each row states what the
% cited source is allowed to justify in the network model and what it does not
% justify.

sourceId = { ...
    'MoTe2_pressure_NatCommun2016'; ...
    'MoTe2_pressure_NatCommun2016_duplicate'; ...
    'MoTe2_gap_pointcontact_arXiv1805_02470'; ...
    'Ambegaokar_Baratoff_OSTI4700205'; ...
    'MoTe2_edge_supercurrent_OSTI1803173' ...
    };

citationLabel = { ...
    'Qi et al., Nature Communications 7, 11038 (2016)'; ...
    'Duplicate user-provided Nature Communications 7, 11038 source'; ...
    'MoTe2 point-contact spectroscopy / gap-ratio prior, arXiv:1805.02470'; ...
    'Ambegaokar and Baratoff tunnel-junction IcRn relation'; ...
    'MoTe2 edge-supercurrent / field-oscillation study, OSTI 1803173' ...
    };

url = { ...
    'https://www.nature.com/articles/ncomms11038'; ...
    'https://www.nature.com/articles/ncomms11038'; ...
    'https://arxiv.org/abs/1805.02470'; ...
    'https://www.osti.gov/biblio/4700205'; ...
    'https://www.osti.gov/biblio/1803173' ...
    };

priorClass = { ...
    'MoTe2 superconducting scale'; ...
    'Duplicate source bookkeeping'; ...
    'Gap and weak-link scale'; ...
    'Tunnel weak-link critical current'; ...
    'Field/phase limitation' ...
    };

modelUse = { ...
    'Justifies low unenhanced Tc baseline, bounded enhanced local Tc population, and strong lattice sensitivity.'; ...
    'Stored once in analysis; retained here only to preserve the user-provided reference list.'; ...
    'Provides a narrow prior for alpha_gap = 2 Delta / kB Tc near 3.7 +/- 0.4.'; ...
    'Constrains tunnel-like weak-link Ic Rn(T) instead of allowing independent arbitrary Ic per link.'; ...
    'Motivates edge/loop/weak-link field sensitivity while marking phase-coherent oscillations as outside the resistor-network core.' ...
    };

modelBoundary = { ...
    'Do not convert hydrostatic pressure directly into local uniaxial strain in the lithographic stressor geometry.'; ...
    'Do not double-weight the same Nature Communications source.'; ...
    'Do not claim the local strained domains have directly measured gaps unless device-specific spectroscopy exists.'; ...
    'Use as a tunnel/crack-like hypothesis; continuous intraflake regions may be SNS/constriction-like instead.'; ...
    'Do not tune a scalar field-resistance term to reproduce oscillation periods; a phase-aware Josephson module would be required.' ...
    };

implementedHook = { ...
    'Tc baseline/enhanced bounds and correlated mechanical/Raman proxy fields.'; ...
    'Reference-table duplicate flag only.'; ...
    'v7.4.6/v7.5 alpha_gap sweep and gap-derived Ic scale.'; ...
    'v7.4.6/v7.5 AB-like IcRn scale for crack/tunnel-like links.'; ...
    'v7.5 hypothesis boundary: field oscillations are not part of the core fitted score.' ...
    };

coreStatus = { ...
    'implemented_as_prior'; ...
    'bookkeeping_only'; ...
    'implemented_as_prior'; ...
    'implemented_as_model_hypothesis'; ...
    'explicitly_out_of_scope_for_core_model' ...
    };

notes = { ...
    'Use to bound local Tc ranges and motivate mechanical coupling, not to infer a unique Tc(epsilon) law.'; ...
    'Items 1 and 2 in the user list are identical links.'; ...
    'This prior narrows alpha_gap but should remain shared/global, not link-by-link.'; ...
    'Good for low-transparency links; SNS/constriction links should use a separate normalized class factor.'; ...
    'Safe thesis framing: the present network can discuss suppression/envelope trends, not fluxoid-period extraction.' ...
    };

priors = table(sourceId, citationLabel, url, priorClass, modelUse, ...
    modelBoundary, implementedHook, coreStatus, notes);
end
