function h = plot_v75_literature_prior_map(priors)
%PLOT_V75_LITERATURE_PRIOR_MAP Thesis-facing source/prior summary.

h = figure('Name', 'v7.5 literature-prior map', 'Color', 'w', ...
    'Position', [100 100 1450 820]);
tiledlayout(2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

nexttile;
classes = unique(priors.priorClass);
counts = zeros(size(classes));
for k = 1:numel(classes)
    counts(k) = sum(strcmp(priors.priorClass, classes{k}));
end
bar(counts, 'FaceColor', [0.20 0.55 0.85]);
set(gca, 'XTick', 1:numel(classes), 'XTickLabel', classes, ...
    'XTickLabelRotation', 25, 'Color', 'w', 'XColor', 'k', 'YColor', 'k');
ylabel('source count');
title('literature roles');
grid on;

nexttile;
statuses = {'implemented_as_prior', 'implemented_as_model_hypothesis', ...
    'explicitly_out_of_scope_for_core_model', 'bookkeeping_only'};
statusCounts = zeros(size(statuses));
for k = 1:numel(statuses)
    statusCounts(k) = sum(strcmp(priors.coreStatus, statuses{k}));
end
bar(statusCounts, 'FaceColor', [0.40 0.70 0.35]);
set(gca, 'XTick', 1:numel(statuses), 'XTickLabel', statuses, ...
    'XTickLabelRotation', 25, 'Color', 'w', 'XColor', 'k', 'YColor', 'k');
ylabel('source count');
title('implementation status');
grid on;

nexttile;
axis off;
allowed = { ...
    'Allowed uses in v7.5:', ...
    '1. Bound low/enhanced local Tc scales; do not infer a unique strain law.', ...
    '2. Tie Delta, Ic, and Rn through shared gap/weak-link priors.', ...
    '3. Compare SNS/constriction-like and crack/tunnel-like link classes.', ...
    '4. Keep distributed local Tc and 2D connectivity as the core transport mechanism.', ...
    '5. Treat field data as envelope/suppression evidence, not phase-period proof.' ...
    };
text(0.02, 0.95, allowed, 'Units', 'normalized', 'VerticalAlignment', 'top', ...
    'FontSize', 13, 'Interpreter', 'none', 'Color', 'k');

nexttile;
axis off;
guardrails = { ...
    'Explicit guardrails:', ...
    '- Literature priors are not replacement measurements for local strain.', ...
    '- Hydrostatic pressure is not converted directly to lithographic uniaxial strain.', ...
    '- alpha_gap is shared/global, not link-by-link fitting freedom.', ...
    '- AB is a tunnel-link hypothesis; SNS/constrictions remain a separate class.', ...
    '- Fluxoid/edge-supercurrent oscillations require a future phase-aware model.' ...
    };
text(0.02, 0.95, guardrails, 'Units', 'normalized', 'VerticalAlignment', 'top', ...
    'FontSize', 13, 'Interpreter', 'none', 'Color', 'k');

sgtitle('v7.5 literature priors as constrained model inputs', ...
    'FontWeight', 'bold', 'Color', 'k');
end
