function opts = make_physics_case_options()
%MAKE_PHYSICS_CASE_OPTIONS Defaults for v6.5 physics-informed case tests.
%
% v6.5 translates literature-motivated physical hypotheses into named model
% cases instead of treating every Raman/coupling choice as an abstract knob.

opts = make_domain_percolation_options();
opts.devices = {'AS002','AS005','AS006'};
opts.T_vec = linspace(0.05, 2.20, 120);
opts.Iprobe = 1e-8;

opts.caseIDs = {'baseline_smooth', ...
    'case_A_inplane_Tc', ...
    'case_B_outofplane_weaklinks', ...
    'case_C_crack_edge_domains', ...
    'case_D_boundary_lane', ...
    'case_E_contact_relaxation'};

opts.caseLabels = {'baseline', ...
    'A: in-plane \rightarrow T_c', ...
    'B: out-of-plane \rightarrow weak links', ...
    'C: crack edge domains', ...
    'D: boundary lane', ...
    'E: contact relaxation'};

opts.percolation.scResistanceFraction = 0.20;
opts.percolation.snapshotT_K = [0.05 0.50 1.00 1.40];

opts.combinedScore.metricWeight = 1.0;
opts.combinedScore.shapeWeight = 1.0;

end
