function [rawScores, sourceStatus] = load_v77_candidate_score_tables(opts)
%LOAD_V77_CANDIDATE_SCORE_TABLES Read available v7.4.x candidate CSVs.

rawScores = table();
n = numel(opts.sources);
version = strings(n, 1);
role = strings(n, 1);
scoreFile = strings(n, 1);
loaded = false(n, 1);
rowCount = zeros(n, 1);
note = strings(n, 1);

for k = 1:n
    src = opts.sources(k);
    version(k) = string(src.version);
    role(k) = string(src.role);
    scoreFile(k) = string(src.scoreFile);

    if exist(src.scoreFile, 'file')
        T = read_v77_table(src.scoreFile);
        T.sourceVersion = repmat(string(src.version), height(T), 1);
        T.sourceRole = repmat(string(src.role), height(T), 1);
        T.sourceFile = repmat(string(src.scoreFile), height(T), 1);
        T = normalize_v77_score_table(T);
        rawScores = append_tables_with_union(rawScores, T);
        loaded(k) = true;
        rowCount(k) = height(T);
        note(k) = "loaded";
    else
        note(k) = "missing; regenerate this v7.4.x sweep if you want it included";
    end
end

sourceStatus = table(version, role, scoreFile, loaded, rowCount, note);

[rawScores, seedStatus] = append_v77_seed_ledgers(rawScores, opts);
if ~isempty(seedStatus)
    sourceStatus = [sourceStatus; seedStatus]; %#ok<AGROW>
end

end

function T = read_v77_table(filePath)
%READ_V77_TABLE Compatibility wrapper for MATLAB versions before TextType.
try
    T = readtable(filePath, 'TextType', 'string');
catch
    T = readtable(filePath);
end
end

function T = normalize_v77_score_table(T)
%NORMALIZE_V77_SCORE_TABLE Reduce type drift across independently generated CSVs.
%
% The v7.4.x ledgers were created over several iterations.  A label column can
% therefore be string in one CSV and cellstr/char in another, which makes
% vertical table concatenation fail.  Normalize the fields v7.7 groups by
% before taking the union append.

textVars = ["device", "sourceVersion", "sourceRole", "sourceFile", ...
    "caseName", "caseLabel", "description", "topology", ...
    "calibrationMode", "linkClass", "mechanism", "modelFamily"];
for v = textVars
    name = char(v);
    if has_var(T, name) && ~isstring(T.(name))
        T.(name) = string(T.(name));
    end
end

if has_var(T, 'seed') && ~isnumeric(T.seed)
    T.seed = str2double(string(T.seed));
end
end

function A = append_tables_with_union(A, B)
if isempty(A)
    A = B;
    return;
end

varsA = string(A.Properties.VariableNames);
varsB = string(B.Properties.VariableNames);
allVars = unique([varsA varsB], 'stable');

for v = allVars
    name = char(v);
    if ~ismember(v, varsA)
        A.(name) = missing_column(height(A), B, name);
    end
    if ~ismember(v, varsB)
        B.(name) = missing_column(height(B), A, name);
    end
end

A = A(:, cellstr(allVars));
B = B(:, cellstr(allVars));
A = [A; B];
end

function col = missing_column(n, templateTable, varName)
if any(strcmp(templateTable.Properties.VariableNames, varName))
    sample = templateTable.(varName);
    if isnumeric(sample)
        col = NaN(n, 1);
    elseif islogical(sample)
        col = false(n, 1);
    elseif isstring(sample)
        col = strings(n, 1);
    elseif iscell(sample)
        col = repmat({''}, n, 1);
    else
        col = strings(n, 1);
    end
else
    col = strings(n, 1);
end
end

function [rawScores, sourceStatus] = append_v77_seed_ledgers(rawScores, opts)
%APPEND_V77_SEED_LEDGERS Add optional multi-seed ledgers generated by v7.7.

sourceStatus = table();
if ~isfield(opts, 'multiSeed') || ~isfield(opts.multiSeed, 'ledgerDir') || ...
        exist(opts.multiSeed.ledgerDir, 'dir') ~= 7
    return;
end

files = dir(fullfile(opts.multiSeed.ledgerDir, '*_seed_*_scores.csv'));
if isempty(files)
    return;
end

n = numel(files);
version = strings(n, 1);
role = strings(n, 1);
scoreFile = strings(n, 1);
loaded = false(n, 1);
rowCount = zeros(n, 1);
note = strings(n, 1);

for k = 1:n
    filePath = fullfile(files(k).folder, files(k).name);
    [version(k), role(k)] = infer_seed_source_metadata(files(k).name);
    scoreFile(k) = string(filePath);

    try
        T = read_v77_table(filePath);
        if ~has_var(T, 'sourceVersion')
            T.sourceVersion = repmat(version(k), height(T), 1);
        end
        if ~has_var(T, 'sourceRole')
            T.sourceRole = repmat(role(k), height(T), 1);
        end
        if ~has_var(T, 'sourceFile')
            T.sourceFile = repmat(string(filePath), height(T), 1);
        end
        if ~has_var(T, 'seed')
            T.seed = repmat(infer_seed_from_name(files(k).name), height(T), 1);
        end

        T = normalize_v77_score_table(T);
        rawScores = append_tables_with_union(rawScores, T);
        loaded(k) = true;
        rowCount(k) = height(T);
        note(k) = "loaded seed ledger";
    catch ME
        note(k) = "failed seed ledger: " + string(ME.message);
    end
end

sourceStatus = table(version, role, scoreFile, loaded, rowCount, note);

end

function tf = has_var(T, varName)
tf = any(strcmp(T.Properties.VariableNames, varName));
end

function [version, role] = infer_seed_source_metadata(fileName)
name = string(fileName);
if contains(name, "v7_4_5") || contains(name, "v745")
    version = "v7.4.5";
    role = "runtime_cleaned_physical_bottleneck_Wij_seed";
elseif contains(name, "v7_4_6") || contains(name, "v746")
    version = "v7.4.6";
    role = "gap_tied_weak_links_seed";
else
    version = "seed_ledger";
    role = "unknown_seed_source";
end
end

function seed = infer_seed_from_name(fileName)
tokens = regexp(char(fileName), 'seed[_-](\d+)', 'tokens', 'once');
if isempty(tokens)
    seed = NaN;
else
    seed = str2double(tokens{1});
end
end
