function h = plot_v77_mechanism_ranking(mechanismSummary, gateSummary, sourceStatus, opts)
%PLOT_V77_MECHANISM_RANKING Thesis-style v7.7 mechanism/gate summary.

h = figure('Name', 'v7.7 multi-observable mechanism ranking', ...
    'Color', 'w', 'Position', [80 80 1450 850]);
set(h, 'InvertHardcopy', 'off');
tl = tiledlayout(2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

if isempty(mechanismSummary)
    nexttile;
    axis off;
    text(0.05, 0.8, 'No v7.4.x score tables were found.', ...
        'Units', 'normalized', 'FontSize', 13, 'Color', 'k');
    title(tl, 'v7.7 multi-observable scoring: no inputs loaded');
    apply_v77_light_style(h);
    return;
end

nexttile;
bar(mechanismSummary.meanObjectiveScore, 'FaceColor', [0.20 0.50 0.85], ...
    'EdgeColor', [0.15 0.25 0.35], 'LineWidth', 0.8);
set(gca, 'XTick', 1:height(mechanismSummary), ...
    'XTickLabel', cellstr(mechanismSummary.mechanism), ...
    'XTickLabelRotation', 25);
ylabel('mean objective score');
title('mechanism ranking; lower is better');
grid on;

nexttile;
nShow = min(6, height(mechanismSummary));
componentMatrix = [ ...
    mechanismSummary.meanPrimaryRTScore(1:nShow), ...
    normalize_component(mechanismSummary.meanHeldoutScore(1:nShow)), ...
    normalize_component(mechanismSummary.meanProbeAsymmetryScore(1:nShow)), ...
    mechanismSummary.bestParameterCount(1:nShow) .* opts.weights.complexityPenalty ...
    ];
bar(componentMatrix, 'grouped');
set(gca, 'XTick', 1:nShow, ...
    'XTickLabel', cellstr(mechanismSummary.mechanism(1:nShow)), ...
    'XTickLabelRotation', 25);
ylabel('component scale');
legend({'R(T) shape', 'held-out diagnostic', 'probe asymmetry', 'complexity'}, ...
    'Location', 'northoutside', 'Orientation', 'horizontal');
title('score components for leading mechanisms');
grid on;

nexttile;
gateMatrix = [mechanismSummary.screeningPass, ...
    mechanismSummary.seedCount >= opts.gates.minSeeds & ...
    isfinite(mechanismSummary.seedStdObjectiveScore), ...
    isfinite(mechanismSummary.meanHeldoutScore), ...
    isfinite(mechanismSummary.meanProbeAsymmetryScore), ...
    isfinite(mechanismSummary.ablationZ) & ...
    abs(mechanismSummary.ablationZ) >= opts.gates.minAblationZ, ...
    mechanismSummary.physicalClaimPass];
imagesc(double(gateMatrix));
colormap(gca, [0.85 0.85 0.85; 0.20 0.60 0.30]);
caxis([0 1]);
set(gca, 'XTick', 1:6, 'XTickLabel', ...
    {'screen', 'seeds', 'held-out', 'asym.', 'Z', 'claim'}, ...
    'XTickLabelRotation', 25, 'YTick', 1:height(mechanismSummary), ...
    'YTickLabel', cellstr(mechanismSummary.mechanism));
title('physical-claim gates');

nexttile;
axis off;
sourceRoleText = string(sourceStatus.role);
isSeedLedger = contains(sourceRoleText, "seed", 'IgnoreCase', true);
isBaseLedger = ~isSeedLedger;
baseLoaded = sum(sourceStatus.loaded & isBaseLedger);
baseTotal = sum(isBaseLedger);
seedLoaded = sum(sourceStatus.loaded & isSeedLedger);
seedTotal = sum(isSeedLedger);

loadedText = sprintf('%d/%d base v7.4.x source tables loaded', ...
    baseLoaded, baseTotal);
if seedTotal > 0
    seedText = sprintf('%d/%d multi-seed ledgers loaded', ...
        seedLoaded, seedTotal);
else
    seedText = '0 multi-seed ledgers loaded';
end
if baseLoaded < baseTotal
    missingText = 'Missing base ledgers are omitted, not scored as failures.';
else
    missingText = 'All configured base ledgers were available.';
end
if seedLoaded < opts.gates.minSeeds
    seedGateText = sprintf('Seed/Z/claim gates stay gray until >= %d seeds per mechanism.', ...
        opts.gates.minSeeds);
else
    seedGateText = 'Seed ledgers are available for ablation-Z gate evaluation.';
end
bestLine = sprintf('Best current screening case: %s (%s)', ...
    mechanismSummary.bestCaseName(1), mechanismSummary.mechanism(1));
seedLine = sprintf('Seed rule: physical claim requires >= %d disorder seeds.', ...
    opts.gates.minSeeds);
zLine = sprintf('Ablation-Z rule: |Z| >= %.1f relative to seed variability.', ...
    opts.gates.minAblationZ);
ruleLines = { ...
    loadedText, ...
    seedText, ...
    missingText, ...
    bestLine, ...
    seedLine, ...
    zLine, ...
    seedGateText, ...
    '', ...
    'Interpretation:', ...
    'v7.7 ranks mechanisms from real v7.4.x ledgers.', ...
    'It does not yet prove a mechanism if seed variability is unavailable.', ...
    'Single-device/single-seed improvements remain screening evidence.'};
text(0.03, 0.95, strjoin(ruleLines, newline), ...
    'Units', 'normalized', 'VerticalAlignment', 'top', ...
    'Interpreter', 'none', 'FontSize', 11, 'Color', 'k');
title('how to read this figure');

title(tl, 'v7.7 multi-observable scoring across real v7.4.x candidates', ...
    'Color', 'k', 'FontWeight', 'bold');
apply_v77_light_style(h);

end

function y = normalize_component(x)
y = x;
finite = isfinite(y);
if any(finite)
    y(finite) = y(finite) ./ max(max(y(finite)), eps);
end
y(~finite) = 0;
end
