function cases = make_v75_hypothesis_cases()
%MAKE_V75_HYPOTHESIS_CASES Competing model hypotheses for v7.5.
%
% These are thesis-facing hypotheses: each case states which physical
% interpretation is being tested while preserving a compact parameter set.

caseId = { ...
    'H0_baseline_geometry'; ...
    'H1_lattice_sensitive_Tc'; ...
    'H2_gap_tied_SNS_constrictions'; ...
    'H3_gap_tied_crack_tunnel_links'; ...
    'H4_contact_relaxation_anisotropy'; ...
    'H5_phase_field_boundary' ...
    };

hypothesis = { ...
    'Geometry and correlated disorder alone produce the broad normalized transition.'; ...
    'Local superconducting scale follows a bounded lattice-sensitive Tc prior.'; ...
    'Weak boundaries behave like continuous SNS/constriction-like links with gap-tied Ic.'; ...
    'Crack/tear or delaminated regions behave as lower-transparency tunnel-like bottlenecks.'; ...
    'Metal contacts and crystal-axis anisotropy redistribute the effective mechanical response and weak-link transparency.'; ...
    'Field oscillations require phase-aware loops/edges and are intentionally not fit by the core scalar network.' ...
    };

literaturePriorIds = { ...
    'MoTe2_pressure_NatCommun2016'; ...
    'MoTe2_pressure_NatCommun2016'; ...
    'MoTe2_gap_pointcontact_arXiv1805_02470; Ambegaokar_Baratoff_OSTI4700205'; ...
    'MoTe2_gap_pointcontact_arXiv1805_02470; Ambegaokar_Baratoff_OSTI4700205'; ...
    'MoTe2_pressure_NatCommun2016'; ...
    'MoTe2_edge_supercurrent_OSTI1803173' ...
    };

parameterFields = { ...
    'Rn, Tc, correlated disorder, Hall-bar geometry'; ...
    'Tc baseline, enhanced Tc range, mechanical/Raman proxy'; ...
    'Delta(Tc), Rn, class factor F_SNS(T/Tc), global transparency'; ...
    'Delta(Tc), Rn, AB-like F_tunnel(T/Tc), crack transparency'; ...
    'contact-relaxation mask, anisotropic W_ij, current-crowding score'; ...
    'not fitted in core model; future Josephson/phase module only' ...
    };

allowedClaim = { ...
    'Tests whether two-dimensional connectivity is necessary before adding extra physics.'; ...
    'Tests whether bounded enhanced-Tc heterogeneity improves transport shape.'; ...
    'Tests whether gap-tied weak boundaries explain broad tails and top/bottom differences.'; ...
    'Tests whether low-transparency bottlenecks are needed near cracks or discontinuities.'; ...
    'Tests whether contacts and anisotropy must be represented as spatially structured priors.'; ...
    'Defines a limit of the present model, preventing overinterpretation of magnetic oscillations.' ...
    };

notAllowedClaim = { ...
    'Does not infer a microscopic strain tensor or order parameter.'; ...
    'Does not convert pressure directly to uniaxial strain.'; ...
    'Does not fit a separate Ic(T) law for every link.'; ...
    'Does not prove an insulating tunnel junction exists.'; ...
    'Does not prove contact strain values without direct strain mapping.'; ...
    'Does not claim quantitative vortex/fluxoid-period prediction.' ...
    };

coreModelStatus = { ...
    'implemented'; ...
    'implemented_as_prior'; ...
    'implemented_as_gap_weaklink_case'; ...
    'implemented_as_gap_weaklink_case'; ...
    'implemented_as_competing_topology'; ...
    'boundary_only' ...
    };

cases = table(caseId, hypothesis, literaturePriorIds, parameterFields, ...
    allowedClaim, notAllowedClaim, coreModelStatus);
end
