function h = plot_v75_hypothesis_case_map(cases)
%PLOT_V75_HYPOTHESIS_CASE_MAP Visual map of v7.5 competing hypotheses.

featureLabels = {'geometry', 'Tc prior', 'Delta(Tc)', 'Ic-Rn', ...
    'W_{ij} topology', 'field/phase boundary'};
caseLabels = {'H0', 'H1', 'H2', 'H3', 'H4', 'H5'};
caseKey = { ...
    'Competing hypotheses retained for v7.5:', ...
    ' ', ...
    'H0 baseline: geometry + correlated disorder only.', ...
    'H1 lattice-sensitive T_c: bounded local superconducting scale.', ...
    'H2 SNS/constriction links: continuous weak boundaries with gap-tied I_c.', ...
    'H3 crack/tunnel links: lower-transparency bottlenecks with AB-like I_cR_N.', ...
    'H4 contacts/anisotropy: metal relaxation and directional transparency.', ...
    'H5 phase/field boundary: oscillations require a future phase-aware module.' ...
    };

M = [ ...
    1 0 0 0 0 0; ...
    1 1 0 0 0 0; ...
    1 1 1 1 1 0; ...
    1 1 1 1 1 0; ...
    1 1 0 0 1 0; ...
    0 0 0 0 0 1 ...
    ];

h = figure('Name', 'v7.5 hypothesis case map', 'Color', 'w', ...
    'Position', [80 80 1650 760]);
tiledlayout(1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

nexttile;
imagesc(M);
colormap(gca, [0.94 0.94 0.94; 0.15 0.50 0.80]);
cb = colorbar;
cb.Ticks = [0 1];
cb.TickLabels = {'not active', 'active'};
cb.Color = 'k';
set(gca, 'XTick', 1:numel(featureLabels), 'XTickLabel', featureLabels, ...
    'XTickLabelRotation', 35, 'YTick', 1:height(cases), ...
    'YTickLabel', caseLabels, 'Color', 'w', 'XColor', 'k', 'YColor', 'k', ...
    'TickLabelInterpreter', 'none');
title('case-to-physics mapping');

nexttile;
axis off;
text(0.02, 0.98, caseKey, 'Units', 'normalized', 'VerticalAlignment', 'top', ...
    'FontSize', 12.0, 'Interpreter', 'none', 'Color', 'k');

sgtitle('v7.5 competing hypotheses: literature-constrained, not first-principles', ...
    'FontWeight', 'bold', 'Color', 'k');
end
