function cfg = phase5_config(rootDir)
%PHASE5_CONFIG Configuration for the reduced six-device transfer plan.

if nargin < 1 || isempty(rootDir)
    rootDir = fileparts(fileparts(mfilename('fullpath')));
end

repoRoot = fileparts(rootDir);

cfg = struct();
cfg.modelVersion = 'v8.0-phase5';
cfg.device = 'AS006';
cfg.repoRoot = repoRoot;
cfg.rootDir = rootDir;

cfg.phase4DecisionFile = fullfile(rootDir, 'outputs', ...
    'v8_0_phase4_identifiability_pruning', ...
    'AS006_v8_0_phase4_pruning_decisions.csv');

cfg.outputDir = fullfile(rootDir, 'outputs', 'v8_0_phase5_transfer_plan');
cfg.ledgerDir = fullfile(cfg.outputDir, 'device_ledgers');
cfg.manifestFile = fullfile(cfg.outputDir, 'RUN_MANIFEST.json');
cfg.candidateSetFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_transfer_candidate_set.csv');
cfg.devicePlanFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_device_plan.csv');
cfg.validationGateFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_validation_gates.csv');
cfg.dataManifestFile = fullfile(cfg.outputDir, 'phase5_data_manifest.csv');
cfg.transferScoreFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_transfer_scores.csv');
cfg.deviceSummaryFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_device_summary.csv');
cfg.leaveOneOutFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_leave_one_device_out.csv');
cfg.gateResultFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_gate_results.csv');
cfg.runStatusFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_device_run_status.csv');
cfg.figureBaseFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_transfer_summary');

cfg.phase4MechanismSummaryFile = fullfile(rootDir, 'outputs', ...
    'v8_0_phase4_identifiability_pruning', ...
    'AS006_v8_0_phase4_mechanism_identifiability.csv');
cfg.phase4CandidateScoreFile = fullfile(rootDir, 'outputs', ...
    'v8_0_phase4_identifiability_pruning', ...
    'AS006_v8_0_phase4_candidate_scores.csv');

cfg.transferPrimary = [ ...
    "combined physical bottleneck"; ...
    "contact-relaxed weak links"; ...
    "crack/tunnel-like weak links" ...
    ];
cfg.requiredControls = [ ...
    "no weak links"; ...
    "uniform weak links"; ...
    "shuffled weak links"; ...
    "central-lane / 1D-like" ...
    ];
cfg.diagnosticControls = [ ...
    "anisotropic control" ...
    ];
cfg.diagnosticHold = [ ...
    "boundary/SNS-inspired constriction" ...
    ];

cfg.devices = ["AS001"; "AS002"; "AS003"; "AS004"; "AS005"; "AS006"];
cfg.trainingAnchorDevice = "AS006";
cfg.validationMode = "six_device_transfer_with_leave_one_device_out";

cfg.runDeviceSweeps = false;
cfg.allowCachedAnchorEvidence = true;
cfg.requiredEvidenceDeviceFraction = 0.80;
cfg.levelA.enabled = true;
cfg.levelA.description = 'R(T) transfer across all six devices';
cfg.observableWeights.rtCurve = 0.45;
cfg.observableWeights.transitionMetrics = 0.25;
cfg.observableWeights.probe = 0.15;
cfg.observableWeights.nonlinear = 0.15;
cfg.sourceVersion = 'v7.4.6';
cfg.sourceScript = fullfile(repoRoot, 'matlab_v7_4_6_files', ...
    'run_v746_as006_gap_weaklink_sweep.m');
cfg.sourceOutputBase = fullfile(repoRoot, 'matlab_v7_4_6_files', 'outputs');
cfg.transferTopologyFilter = [ ...
    "combined"; ...
    "contact_relaxation"; ...
    "tear_lane"; ...
    "none"; ...
    "uniform"; ...
    "shuffled"; ...
    "central_lane" ...
    ];
cfg.alphaGapValues = [3.3 3.7 4.1];
cfg.gammaWValues = [0.05 0.10 0.20 0.40 0.70];
cfg.pWValues = [0.05 0.10 0.20 0.30];
cfg.runFullFieldMaps = false;
cfg.reuseExistingScreeningTables = false;

phase3Cfg = v800.phase3_config(rootDir);

cfg.phase5A.enabled = true;
cfg.phase5A.description = 'Frozen-basin primary R(T) transfer across AS001-AS006';
cfg.phase5A.rtManifestFile = fullfile(cfg.outputDir, 'phase5_rt_manifest.csv');
cfg.phase5A.frozenBasinFile = fullfile(cfg.outputDir, ...
    'phase5_frozen_basin_set.csv');
cfg.phase5A.frozenTransferLedgerFile = fullfile(cfg.outputDir, ...
    'phase5_frozen_transfer_ledger.csv');
cfg.phase5A.summaryFile = fullfile(cfg.outputDir, ...
    'phase5_levelA_device_summary.csv');
cfg.phase5A.leaveOneOutFile = fullfile(cfg.outputDir, ...
    'phase5_levelA_leave_one_device_out.csv');
cfg.phase5A.gateResultFile = fullfile(cfg.outputDir, ...
    'phase5_levelA_gate_results.csv');
cfg.phase5A.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase5_levelA_rt_transfer_summary');
cfg.phase5A.parameterBasinScoreTolerance = 0.02;
cfg.phase5A.maxBasinRowsPerTrack = 10;
cfg.phase5A.commonSeeds = phase3Cfg.seeds;
cfg.phase5A.primaryDataSourcePolicy = 'publication_main_4p_for_Level_A';
cfg.phase5A.maxTemperaturePoints = 120;
cfg.phase5A.Iprobe_A = 1e-8;
cfg.phase5A.score.rtScoreGridPoints = 160;
cfg.phase5A.score.weightCurve = 0.50;
cfg.phase5A.score.weightOnset = 0.20;
cfg.phase5A.score.weightWidth = 0.15;
cfg.phase5A.score.weightLowT = 0.15;
cfg.phase5A.score.onsetScale_K = 0.35;
cfg.phase5A.score.widthScale_K = 0.35;

cfg.phase5B.enabled = true;
cfg.phase5B.description = 'Held-out secondary-probe and hierarchical transfer validation';
cfg.phase5B.freezeManifestFile = fullfile(cfg.outputDir, ...
    'phase5B_frozen_phase5A_archive.csv');
cfg.phase5B.secondaryManifestFile = fullfile(cfg.outputDir, ...
    'phase5B_secondary_probe_manifest.csv');
cfg.phase5B.secondaryLedgerFile = fullfile(cfg.outputDir, ...
    'phase5B_secondary_probe_ledger.csv');
cfg.phase5B.deviceEvidenceFile = fullfile(cfg.outputDir, ...
    'phase5B_device_evidence_table.csv');
cfg.phase5B.classHeldoutFile = fullfile(cfg.outputDir, ...
    'phase5B_class_heldout_validation.csv');
cfg.phase5B.activationPlanFile = fullfile(cfg.outputDir, ...
    'phase5B_activation_law_plan.csv');
cfg.phase5B.gateResultFile = fullfile(cfg.outputDir, ...
    'phase5B_hierarchical_gate_results.csv');
cfg.phase5B.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase5B_secondary_hierarchy_summary');
cfg.phase5B.maxTemperaturePoints = 120;
cfg.phase5B.Iprobe_A = cfg.phase5A.Iprobe_A;
cfg.phase5B.secondaryWeight = 0.55;
cfg.phase5B.asymmetryWeight = 0.45;
cfg.phase5B.complexityPenaltyLambda = 0.01;
cfg.phase5B.asymmetryOrderingTolerance = 0.08;
cfg.phase5B.asymmetryOnsetThreshold = 0.08;
cfg.phase5B.halfEncapsulatedDevices = ["AS002"; "AS004"; "AS006"];
cfg.phase5B.controlDevices = ["AS001"; "AS003"];
cfg.phase5B.crackDevices = "AS005";
cfg.phase5B.structuredRegimeDevices = ["AS004"; "AS005"; "AS006"];

cfg.phase5B1.enabled = true;
cfg.phase5B1.description = 'Global activation-law validation for half-encapsulated transfer';
cfg.phase5B1.baselineArchiveFile = fullfile(cfg.outputDir, ...
    'phase5B1_frozen_5B_baseline_archive.csv');
cfg.phase5B1.deviceActivationFile = fullfile(cfg.outputDir, ...
    'phase5B1_device_activation_inputs.csv');
cfg.phase5B1.fitLedgerFile = fullfile(cfg.outputDir, ...
    'phase5B1_activation_fit_ledger.csv');
cfg.phase5B1.heldoutFile = fullfile(cfg.outputDir, ...
    'phase5B1_activation_heldout_validation.csv');
cfg.phase5B1.secondaryPreservationFile = fullfile(cfg.outputDir, ...
    'phase5B1_secondary_preservation.csv');
cfg.phase5B1.gateResultFile = fullfile(cfg.outputDir, ...
    'phase5B1_activation_gate_results.csv');
cfg.phase5B1.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase5B1_activation_law_summary');
cfg.phase5B1.F0_N_per_m = 40;
cfg.phase5B1.lambdaMax = 1;
cfg.phase5B1.lambdaBGrid = 0:0.05:1;
cfg.phase5B1.lambdaCGrid = 0:0.05:1;
cfg.phase5B1.qGrid = [0.5 0.75 1.0 1.25 1.5 2.0 2.5 3.0];
cfg.phase5B1.lambdaLowerBound = 0;
cfg.phase5B1.lambdaUpperBound = 1;
cfg.phase5B1.qLowerBound = 0.5;
cfg.phase5B1.qUpperBound = 3.0;
cfg.phase5B1.qComplexityPenalty = cfg.phase5B.complexityPenaltyLambda;
cfg.phase5B1.halfEncapsulatedForce_N_per_m = table( ...
    ["AS002"; "AS004"; "AS006"], [-3; -20; -40], ...
    'VariableNames', {'device','film_force_N_per_m'});
cfg.phase5B1.crackDevice = "AS005";

cfg.phase5B2.enabled = true;
cfg.phase5B2.description = 'Full-series global activation-law consolidation';
cfg.phase5B2.baselineArchiveFile = fullfile(cfg.outputDir, ...
    'phase5B2_frozen_5B1_baseline_archive.csv');
cfg.phase5B2.fullSeriesFitLedgerFile = fullfile(cfg.outputDir, ...
    'phase5B2_full_series_fit_ledger.csv');
cfg.phase5B2.devicePredictionFile = fullfile(cfg.outputDir, ...
    'phase5B2_full_series_device_predictions.csv');
cfg.phase5B2.jointComparisonFile = fullfile(cfg.outputDir, ...
    'phase5B2_joint_model_comparison.csv');
cfg.phase5B2.as004ProfileFile = fullfile(cfg.outputDir, ...
    'phase5B2_AS004_lambda_profile.csv');
cfg.phase5B2.uncertaintyFile = fullfile(cfg.outputDir, ...
    'phase5B2_activation_uncertainty_by_seed.csv');
cfg.phase5B2.uncertaintySummaryFile = fullfile(cfg.outputDir, ...
    'phase5B2_activation_uncertainty_summary.csv');
cfg.phase5B2.gateResultFile = fullfile(cfg.outputDir, ...
    'phase5B2_consolidation_gate_results.csv');
cfg.phase5B2.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase5B2_full_series_activation_summary');
cfg.phase5B2.lambdaBGrid = cfg.phase5B1.lambdaBGrid;
cfg.phase5B2.qGrid = cfg.phase5B1.qGrid;
cfg.phase5B2.lambdaProfileGrid = 0:0.025:1;
cfg.phase5B2.requireStrictHeldoutProtectedPasses = 2;

cfg.phase5C.enabled = true;
cfg.phase5C.description = 'Synthetic mechanism-recovery study';
cfg.phase5C.outputDir = cfg.outputDir;
cfg.phase5C.syntheticManifestFile = fullfile(cfg.outputDir, ...
    'phase5C_synthetic_recovery_manifest.csv');
cfg.phase5C.labelPolicyFile = fullfile(cfg.outputDir, ...
    'phase5C_label_mapping_policy.csv');
cfg.phase5C.scoreLedgerFile = fullfile(cfg.outputDir, ...
    'phase5C_synthetic_score_ledger.csv');
cfg.phase5C.recoveryMatrixFile = fullfile(cfg.outputDir, ...
    'phase5C_recovery_matrix.csv');
cfg.phase5C.recoverySummaryFile = fullfile(cfg.outputDir, ...
    'phase5C_recovery_summary.csv');
cfg.phase5C.gateResultFile = fullfile(cfg.outputDir, ...
    'phase5C_synthetic_recovery_gate_results.csv');
cfg.phase5C.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase5C_source_provenance_checkpoint.csv');
cfg.phase5C.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase5C_handoff_status.csv');
cfg.phase5C.misspecManifestFile = fullfile(cfg.outputDir, ...
    'phase5C_misspecification_manifest.csv');
cfg.phase5C.misspecScoreLedgerFile = fullfile(cfg.outputDir, ...
    'phase5C_misspecification_score_ledger.csv');
cfg.phase5C.misspecSummaryFile = fullfile(cfg.outputDir, ...
    'phase5C_misspecification_summary.csv');
cfg.phase5C.misspecGateFile = fullfile(cfg.outputDir, ...
    'phase5C_misspecification_gate_results.csv');
cfg.phase5C.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase5C_synthetic_recovery_summary');
cfg.phase5C.trueModels = ["M0"; "M1"; "M2"; "mixed"];
cfg.phase5C.candidateModels = ["M0"; "M1"; "M2"];
cfg.phase5C.evidenceConfigs = ["primary_only"; "primary_secondary"; ...
    "primary_noise"; "primary_secondary_noise_disorder"];
cfg.phase5C.syntheticSeeds = (1:80).';
cfg.phase5C.temperatureGrid_K = linspace(0.05, 2.20, 120).';
cfg.phase5C.noiseSigmaLow = 0.004;
cfg.phase5C.noiseSigmaRealistic = 0.015;
cfg.phase5C.disorderSigma_Tc_K = 0.035;
cfg.phase5C.normalizationSigma = 0.015;
cfg.phase5C.secondaryWeight = 0.35;
cfg.phase5C.recoveryThreshold = 0.80;
cfg.phase5C.structuredModels = ["M1"; "M2"; "mixed"];
cfg.phase5C.selectedStructuredModels = ["M1"; "M2"];
cfg.phase5C.misspecEvidenceConfigs = ["misspec_primary_only"; ...
    "misspec_primary_secondary"];
cfg.phase5C.misspecTrueModels = ["M0_shifted_broadened"; ...
    "M0_extra_shunt"; "weak_structured_boundary"; ...
    "M1_registration_shift"; "M2_outside_disorder"];
cfg.phase5C.misspecSeeds = (1:40).';
cfg.phase5C.unresolvedMarginThreshold = 0.02;

cfg.phase5D.enabled = true;
cfg.phase5D.description = 'Uncertainty and nuisance calibration for hierarchical classification';
cfg.phase5D.scopeFile = fullfile(cfg.outputDir, ...
    'phase5D_calibration_scope.csv');
cfg.phase5D.nuisanceFamilyFile = fullfile(cfg.outputDir, ...
    'phase5D_M0star_nuisance_family.csv');
cfg.phase5D.scoreDifferencePlanFile = fullfile(cfg.outputDir, ...
    'phase5D_score_difference_calibration_plan.csv');
cfg.phase5D.syntheticSplitFile = fullfile(cfg.outputDir, ...
    'phase5D_calibration_validation_split.csv');
cfg.phase5D.boundarySweepFile = fullfile(cfg.outputDir, ...
    'phase5D_boundary_strength_sweep_plan.csv');
cfg.phase5D.successCriteriaFile = fullfile(cfg.outputDir, ...
    'phase5D_success_criteria.csv');
cfg.phase5D.decisionHierarchyFile = fullfile(cfg.outputDir, ...
    'phase5D_decision_hierarchy.csv');
cfg.phase5D.executionOutputSchemaFile = fullfile(cfg.outputDir, ...
    'phase5D_execution_output_schema.csv');
cfg.phase5D.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase5D_source_provenance_checkpoint.csv');
cfg.phase5D.handoffArchiveFile = fullfile(cfg.outputDir, ...
    'phase5D_phase5C_frozen_handoff_archive.csv');
cfg.phase5D.nuisanceProfileLedgerFile = fullfile(cfg.outputDir, ...
    'phase5D_nuisance_profile_ledger.csv');
cfg.phase5D.deltaSDistributionFile = fullfile(cfg.outputDir, ...
    'phase5D_deltaS_distribution.csv');
cfg.phase5D.calibratedThresholdsFile = fullfile(cfg.outputDir, ...
    'phase5D_calibrated_thresholds.csv');
cfg.phase5D.boundaryDetectionCurvesFile = fullfile(cfg.outputDir, ...
    'phase5D_boundary_detection_curves.csv');
cfg.phase5D.nuisanceBoundaryOccupancyFile = fullfile(cfg.outputDir, ...
    'phase5D_nuisance_boundary_occupancy.csv');
cfg.phase5D.calibrationSelectionLedgerFile = fullfile(cfg.outputDir, ...
    'phase5D_calibration_selection_ledger.csv');
cfg.phase5D.operatingPointFeasibilityFile = fullfile(cfg.outputDir, ...
    'phase5D_operating_point_feasibility.csv');
cfg.phase5D.thresholdRocByEvidenceTierFile = fullfile(cfg.outputDir, ...
    'phase5D_threshold_ROC_by_evidence_tier.csv');
cfg.phase5D.sigmaDeltaSAuditFile = fullfile(cfg.outputDir, ...
    'phase5D_sigmaDeltaS_audit.csv');
cfg.phase5D.uncertaintyComponentDecompositionFile = fullfile(cfg.outputDir, ...
    'phase5D_uncertainty_component_decomposition.csv');
cfg.phase5D.nuisancePenaltySensitivityFile = fullfile(cfg.outputDir, ...
    'phase5D_nuisance_penalty_sensitivity.csv');
cfg.phase5D.internalCalibrationCheckFile = fullfile(cfg.outputDir, ...
    'phase5D_internal_calibration_check.csv');
cfg.phase5D.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase5D_handoff_status.csv');
cfg.phase5D.calibrationGateFile = fullfile(cfg.outputDir, ...
    'phase5D_calibration_gate_results.csv');
cfg.phase5D.validationGateFile = fullfile(cfg.outputDir, ...
    'phase5D_validation_gate_results.csv');
cfg.phase5D.realDeviceReclassificationFile = fullfile(cfg.outputDir, ...
    'phase5D_real_device_reclassification.csv');
cfg.phase5D.calibrationSummaryFigureBaseFile = fullfile(cfg.outputDir, ...
    'phase5D_calibration_summary');

cfg.phase5D2.freezeStatusFile = fullfile(cfg.outputDir, ...
    'phase5D2_freeze_status.csv');
cfg.phase5D2.resultFreezeStatusFile = fullfile(cfg.outputDir, ...
    'phase5D2_result_freeze_status.csv');
cfg.phase5D2.interpretationPolicyFile = fullfile(cfg.outputDir, ...
    'phase5D2_interpretation_policy.csv');
cfg.phase5D2.validationStatusFile = fullfile(cfg.outputDir, ...
    'phase5D2_validation_status.csv');
cfg.phase5D2.frozenInputManifestFile = fullfile(cfg.outputDir, ...
    'phase5D2_frozen_input_manifest.csv');
cfg.phase5D2.realDeviceScoreContextFile = fullfile(cfg.outputDir, ...
    'phase5D2_real_device_score_context.csv');
cfg.phase5D2.deviceEvidenceSynthesisFile = fullfile(cfg.outputDir, ...
    'phase5D2_device_evidence_synthesis.csv');
cfg.phase5D2.finalGateSummaryFile = fullfile(cfg.outputDir, ...
    'phase5D2_final_gate_summary.csv');
cfg.phase5D2.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase5D2_handoff_status.csv');
cfg.phase5D2.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase5D2_result_freeze_summary');

cfg.phase6.modelHierarchyFreezeFile = fullfile(cfg.outputDir, ...
    'phase6_model_hierarchy_freeze.csv');
cfg.phase6.frozenInputManifestFile = fullfile(cfg.outputDir, ...
    'phase6_frozen_input_manifest.csv');
cfg.phase6.sixDeviceEvidenceMatrixFile = fullfile(cfg.outputDir, ...
    'phase6_six_device_evidence_matrix.csv');
cfg.phase6.deviceModelStatusFile = fullfile(cfg.outputDir, ...
    'phase6_device_model_status.csv');
cfg.phase6.evidenceTierAssignmentsFile = fullfile(cfg.outputDir, ...
    'phase6_evidence_tier_assignments.csv');
cfg.phase6.claimHierarchyFile = fullfile(cfg.outputDir, ...
    'phase6_claim_hierarchy.csv');
cfg.phase6.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase6_gate_summary.csv');
cfg.phase6.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase6_handoff_status.csv');
cfg.phase6.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase6_hierarchical_evidence_freeze_summary');

cfg.phase7.scopePolicyFile = fullfile(cfg.outputDir, ...
    'phase7_scope_policy.csv');
cfg.phase7.frozenInputManifestFile = fullfile(cfg.outputDir, ...
    'phase7_frozen_input_manifest.csv');
cfg.phase7.priorEvidenceManifestFile = fullfile(cfg.outputDir, ...
    'phase7_prior_evidence_manifest.csv');
cfg.phase7.perturbationScenarioFile = fullfile(cfg.outputDir, ...
    'phase7_perturbation_scenarios.csv');
cfg.phase7.deviceRobustnessFile = fullfile(cfg.outputDir, ...
    'phase7_device_prior_robustness.csv');
cfg.phase7.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase7_gate_summary.csv');
cfg.phase7.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase7_handoff_status.csv');
cfg.phase7.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase7_raman_mechanical_prior_robustness_summary');
cfg.phase7.registrationShiftPixels = [0 1 2 4].';
cfg.phase7.priorWeightScaleFactors = [0.0 0.5 1.0 1.5].';
cfg.phase7.requirePhase6FrozenInputs = true;
cfg.phase7.allowStatusRelabeling = false;
cfg.phase7.allowClassifierRetuning = false;

cfg.phase7B.frozenInputManifestFile = fullfile(cfg.outputDir, ...
    'phase7B_frozen_input_manifest.csv');
cfg.phase7B.priorVariantLedgerFile = fullfile(cfg.outputDir, ...
    'phase7B_prior_variant_ledger.csv');
cfg.phase7B.geometryMaskSensitivityFile = fullfile(cfg.outputDir, ...
    'phase7B_geometry_mask_sensitivity.csv');
cfg.phase7B.crackMaskSensitivityFile = fullfile(cfg.outputDir, ...
    'phase7B_crack_mask_sensitivity.csv');
cfg.phase7B.ramanRegistrationSensitivityFile = fullfile(cfg.outputDir, ...
    'phase7B_raman_registration_sensitivity.csv');
cfg.phase7B.shuffledPriorControlFile = fullfile(cfg.outputDir, ...
    'phase7B_shuffled_prior_control.csv');
cfg.phase7B.deviceRobustnessAnnotationFile = fullfile(cfg.outputDir, ...
    'phase7B_device_robustness_annotations.csv');
cfg.phase7B.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase7B_gate_summary.csv');
cfg.phase7B.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase7B_handoff_status.csv');
cfg.phase7B.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase7B_source_provenance_checkpoint.csv');
cfg.phase7B.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase7B_geometry_mask_robustness_summary');
cfg.phase7B.phase6LabelsProtected = true;
cfg.phase7B.allowClassifierRetuning = false;
cfg.phase7B.allowStatusRelabeling = false;
cfg.phase7B.referenceVariant = "mechanical_prior_nominal";
cfg.phase7B.variantIds = [ ...
    "geometry_only"; ...
    "mechanical_prior_nominal"; ...
    "mechanical_prior_removed"; ...
    "mechanical_prior_reduced"; ...
    "mechanical_prior_amplified"; ...
    "registration_shift_minus"; ...
    "registration_shift_plus"; ...
    "spatially_shuffled_prior"; ...
    "crack_mask_removed"; ...
    "crack_mask_shifted"; ...
    "boundary_prior_removed"; ...
    "boundary_prior_reduced"; ...
    "boundary_prior_amplified"; ...
    "boundary_mask_shifted" ...
    ];
cfg.phase7B.registrationTransformAvailableDevices = strings(0, 1);
cfg.phase7B.requireCrackSensitivityDevices = "AS005";
cfg.phase7B.requireBoundarySensitivityDevices = ["AS004"; "AS006"];
cfg.phase7B.geometryMaskSensitivityThreshold = 0.05;
cfg.phase7B.registrationSensitivityThreshold = 0.05;
cfg.phase7B.shuffledControlTolerance = 0.02;

cfg.phase8.scopePolicyFile = fullfile(cfg.outputDir, ...
    'phase8_scope_policy.csv');
cfg.phase8.frozenInputManifestFile = fullfile(cfg.outputDir, ...
    'phase8_frozen_input_manifest.csv');
cfg.phase8.numericalTestPlanFile = fullfile(cfg.outputDir, ...
    'phase8_numerical_test_plan.csv');
cfg.phase8.schemaAuditFile = fullfile(cfg.outputDir, ...
    'phase8_schema_audit.csv');
cfg.phase8.reproducibilityAuditFile = fullfile(cfg.outputDir, ...
    'phase8_reproducibility_audit.csv');
cfg.phase8.tolerancePolicyFile = fullfile(cfg.outputDir, ...
    'phase8_tolerance_policy.csv');
cfg.phase8.implementationAuditFile = fullfile(cfg.outputDir, ...
    'phase8_implementation_audit.csv');
cfg.phase8.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase8_gate_summary.csv');
cfg.phase8.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase8_handoff_status.csv');
cfg.phase8.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase8_source_provenance_checkpoint.csv');
cfg.phase8.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase8_numerical_robustness_summary');
cfg.phase8.allowClassifierRetuning = false;
cfg.phase8.allowStatusRelabeling = false;
cfg.phase8.executeExpensiveTransportSweeps = false;
cfg.phase8.scoreAbsTolerance = 1e-9;
cfg.phase8.deltaSContextTolerance = 1e-4;
cfg.phase8.zContextTolerance = 1e-3;
cfg.phase8.meshSizeCandidates = [61; 81; 101; 121; 151];
cfg.phase8.referenceMeshSize = 121;
cfg.phase8.solverToleranceCandidates = [1e-8; 1e-10; 1e-12];
cfg.phase8.normalizationWindowShift_K = [-0.03; 0; 0.03];
cfg.phase8.disorderSeedReplayCount = 10;

cfg.phase8B.frozenInputManifestFile = fullfile(cfg.outputDir, ...
    'phase8B_frozen_input_manifest.csv');
cfg.phase8B.meshReplayFile = fullfile(cfg.outputDir, ...
    'phase8B_mesh_resolution_replay.csv');
cfg.phase8B.solverReplayFile = fullfile(cfg.outputDir, ...
    'phase8B_solver_tolerance_replay.csv');
cfg.phase8B.normalizationReplayFile = fullfile(cfg.outputDir, ...
    'phase8B_normalization_window_replay.csv');
cfg.phase8B.seedReplayFile = fullfile(cfg.outputDir, ...
    'phase8B_disorder_seed_replay.csv');
cfg.phase8B.cachedArtifactReplayFile = fullfile(cfg.outputDir, ...
    'phase8B_cached_artifact_replay.csv');
cfg.phase8B.statusStabilityFile = fullfile(cfg.outputDir, ...
    'phase8B_status_stability_summary.csv');
cfg.phase8B.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase8B_gate_summary.csv');
cfg.phase8B.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase8B_handoff_status.csv');
cfg.phase8B.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase8B_source_provenance_checkpoint.csv');
cfg.phase8B.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase8B_numerical_replay_summary');
cfg.phase8B.allowClassifierRetuning = false;
cfg.phase8B.allowStatusRelabeling = false;
cfg.phase8B.replayMode = 'frozen_context_replay';
cfg.phase8B.strongStructuredDevices = ["AS005"; "AS006"];
cfg.phase8B.expectedNearTieDevices = ["AS001"; "AS004"];
cfg.phase8B.contextDriftReportThreshold = 0.005;
cfg.phase8B.signStabilityMargin = 0.02;

cfg.phase9.frozenInputManifestFile = fullfile(cfg.outputDir, ...
    'phase9_frozen_input_manifest.csv');
cfg.phase9.finalModelSpecificationFile = fullfile(cfg.outputDir, ...
    'phase9_final_model_specification.csv');
cfg.phase9.finalDeviceConclusionLedgerFile = fullfile(cfg.outputDir, ...
    'phase9_final_device_conclusion_ledger.csv');
cfg.phase9.evidenceHierarchyFile = fullfile(cfg.outputDir, ...
    'phase9_evidence_hierarchy.csv');
cfg.phase9.claimHierarchyFile = fullfile(cfg.outputDir, ...
    'phase9_claim_hierarchy.csv');
cfg.phase9.modelLimitationsFile = fullfile(cfg.outputDir, ...
    'phase9_model_limitations.csv');
cfg.phase9.finalFigureManifestFile = fullfile(cfg.outputDir, ...
    'phase9_final_figure_manifest.csv');
cfg.phase9.finalTableManifestFile = fullfile(cfg.outputDir, ...
    'phase9_final_table_manifest.csv');
cfg.phase9.deferredWorkFile = fullfile(cfg.outputDir, ...
    'phase9_deferred_work.csv');
cfg.phase9.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase9_gate_summary.csv');
cfg.phase9.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase9_handoff_status.csv');
cfg.phase9.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase9_source_provenance_checkpoint.csv');
cfg.phase9.ramanRegistrationDiagnosticFile = fullfile(cfg.outputDir, ...
    'phase9_raman_registration_disposition.csv');
cfg.phase9.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase9_final_model_package_summary');
cfg.phase9.allowModelRetuning = false;
cfg.phase9.allowDeviceStatusChanges = false;
cfg.phase9.allowMechanismExpansion = false;
cfg.phase9.nextPhase = 'phase10_reproducible_v8_release';

cfg.phase10.releaseManifestFile = fullfile(cfg.outputDir, ...
    'phase10_release_manifest.csv');
cfg.phase10.artifactChecksumFile = fullfile(cfg.outputDir, ...
    'phase10_artifact_checksums.csv');
cfg.phase10.regenerationRecipeFile = fullfile(cfg.outputDir, ...
    'phase10_regeneration_recipe.csv');
cfg.phase10.releaseNotesFile = fullfile(cfg.outputDir, ...
    'phase10_release_notes.csv');
cfg.phase10.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase10_release_gate_summary.csv');
cfg.phase10.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase10_handoff_status.csv');
cfg.phase10.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase10_source_provenance_checkpoint.csv');
cfg.phase10.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase10_reproducible_release_summary');
cfg.phase10.releaseName = 'v8.0 final model package';
cfg.phase10.releaseScope = 'reproducible release dossier; no retuning';
cfg.phase10.allowModelRetuning = false;
cfg.phase10.allowDeviceStatusChanges = false;
cfg.phase10.allowArtifactMutation = false;

cfg.phase11.deviceObservableManifestFile = fullfile(cfg.outputDir, ...
    'phase11_device_observable_manifest.csv');
cfg.phase11.transportDataSchemaFile = fullfile(cfg.outputDir, ...
    'phase11_transport_data_schema.csv');
cfg.phase11.nonlinearDataSchemaFile = fullfile(cfg.outputDir, ...
    'phase11_nonlinear_data_schema.csv');
cfg.phase11.ramanDataSchemaFile = fullfile(cfg.outputDir, ...
    'phase11_raman_data_schema.csv');
cfg.phase11.geometryCoordinateSchemaFile = fullfile(cfg.outputDir, ...
    'phase11_geometry_coordinate_schema.csv');
cfg.phase11.probeMappingFile = fullfile(cfg.outputDir, ...
    'phase11_probe_mapping.csv');
cfg.phase11.registrationAvailabilityFile = fullfile(cfg.outputDir, ...
    'phase11_registration_availability.csv');
cfg.phase11.uncertaintyManifestFile = fullfile(cfg.outputDir, ...
    'phase11_uncertainty_manifest.csv');
cfg.phase11.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase11_gate_summary.csv');
cfg.phase11.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase11_multimodal_handoff_status.csv');
cfg.phase11.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase11_source_provenance_checkpoint.csv');
cfg.phase11.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase11_multimodal_data_architecture_summary');
cfg.phase11.description = 'Unified multimodal data and observable architecture';
cfg.phase11.allowV8StatusChanges = false;
cfg.phase11.allowModelRetuning = false;
cfg.phase11.allowJointForwardFit = false;

cfg.phase12A.ramanRegistrationLedgerFile = fullfile(cfg.outputDir, ...
    'phase12A_raman_registration_ledger.csv');
cfg.phase12A.coordinateTransformManifestFile = fullfile(cfg.outputDir, ...
    'phase12A_coordinate_transform_manifest.csv');
cfg.phase12A.mechanicalInputDefinitionFile = fullfile(cfg.outputDir, ...
    'phase12A_mechanical_input_definition.csv');
cfg.phase12A.registrationGateSummaryFile = fullfile(cfg.outputDir, ...
    'phase12A_registration_gate_summary.csv');
cfg.phase12A.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase12_handoff_status.csv');
cfg.phase12A.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase12A_source_provenance_checkpoint.csv');
cfg.phase12A.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase12A_raman_registration_feasibility_summary');
cfg.phase12A.description = ...
    'Raman registration feasibility and reduced mechanical-input definition';
cfg.phase12A.registrationStatusVocabulary = [ ...
    "registered_quantitative"; ...
    "registered_with_uncertainty"; ...
    "relative_line_coordinate_only"; ...
    "device_association_only"; ...
    "unregistered" ...
    ];
cfg.phase12A.quantitativeRegistrationStatuses = [ ...
    "registered_quantitative"; "registered_with_uncertainty" ...
    ];
cfg.phase12A.allowInventedTransforms = false;
cfg.phase12A.allowTransportRelabeling = false;
cfg.phase12A.allowTransportRetuning = false;
cfg.phase12A.allow2DFieldFromLineScan = false;

cfg.phase12B.mechanicalModelSpecificationFile = fullfile(cfg.outputDir, ...
    'phase12B_mechanical_model_specification.csv');
cfg.phase12B.parameterPriorLedgerFile = fullfile(cfg.outputDir, ...
    'phase12B_parameter_prior_ledger.csv');
cfg.phase12B.deviceGeometryInputsFile = fullfile(cfg.outputDir, ...
    'phase12B_device_geometry_inputs.csv');
cfg.phase12B.mechanicalFieldManifestFile = fullfile(cfg.outputDir, ...
    'phase12B_mechanical_field_manifest.csv');
cfg.phase12B.boundaryTransferResultsFile = fullfile(cfg.outputDir, ...
    'phase12B_boundary_transfer_results.csv');
cfg.phase12B.crackRelaxationResultsFile = fullfile(cfg.outputDir, ...
    'phase12B_crack_relaxation_results.csv');
cfg.phase12B.uncertaintySensitivityFile = fullfile(cfg.outputDir, ...
    'phase12B_uncertainty_sensitivity.csv');
cfg.phase12B.deviceMechanicalSummaryFile = fullfile(cfg.outputDir, ...
    'phase12B_device_mechanical_summary.csv');
cfg.phase12B.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase12B_gate_summary.csv');
cfg.phase12B.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase12B_handoff_status.csv');
cfg.phase12B.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase12B_source_provenance_checkpoint.csv');
cfg.phase12B.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase12B_reduced_mechanical_forward_summary');
cfg.phase12B.description = ...
    'Reduced geometry-driven mechanical forward model';
cfg.phase12B.allowRamanDerivedField = false;
cfg.phase12B.allowTransportRelabeling = false;
cfg.phase12B.allowTransportRetuning = false;
cfg.phase12B.retainComponentsBeforeScalarReduction = true;
cfg.phase12B.transferLength_um = [2.0; 5.0; 10.0];
cfg.phase12B.boundaryLength_um = [1.0; 3.0; 6.0];
cfg.phase12B.crackLength_um = [0.5; 1.5; 4.0];
cfg.phase12B.throughThicknessLength_nm = [10; 30; 80];
cfg.phase12B.nominalCoverageAmplitude = [0.0; 0.35; 0.25; 0.55; 0.70; 0.90];
cfg.phase12B.nominalBoundaryAmplitude = [0.0; 0.25; 0.05; 0.45; 0.35; 0.80];
cfg.phase12B.nominalCrackAmplitude = [0.0; 0.0; 0.0; 0.0; 0.85; 0.0];

cfg.phase12C.ramanForwardModelSpecificationFile = fullfile(cfg.outputDir, ...
    'phase12C_raman_forward_model_specification.csv');
cfg.phase12C.modeResponsePriorLedgerFile = fullfile(cfg.outputDir, ...
    'phase12C_mode_response_prior_ledger.csv');
cfg.phase12C.deviceLevelModePredictionsFile = fullfile(cfg.outputDir, ...
    'phase12C_device_level_mode_predictions.csv');
cfg.phase12C.nonstrainContributionLedgerFile = fullfile(cfg.outputDir, ...
    'phase12C_nonstrain_contribution_ledger.csv');
cfg.phase12C.registeredComparisonStatusFile = fullfile(cfg.outputDir, ...
    'phase12C_registered_comparison_status.csv');
cfg.phase12C.uncertaintySensitivityFile = fullfile(cfg.outputDir, ...
    'phase12C_uncertainty_sensitivity.csv');
cfg.phase12C.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase12C_gate_summary.csv');
cfg.phase12C.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase12C_handoff_status.csv');
cfg.phase12C.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase12C_source_provenance_checkpoint.csv');
cfg.phase12C.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase12C_raman_forward_feasibility_summary');
cfg.phase12C.description = ...
    'Mode-specific Raman forward-model feasibility';
cfg.phase12C.ramanModes = ["A1g_like"; "E2g_like"; "low_frequency_like"];
cfg.phase12C.comparisonDevices = ["AS002"; "AS005"; "AS006"];
cfg.phase12C.allowRegisteredSpatialComparison = false;
cfg.phase12C.allowCoefficientFitByDevice = false;
cfg.phase12C.allowTransportCoupling = false;
cfg.phase12C.allowAbsoluteStrainInference = false;
cfg.phase12C.predictionScope = ...
    "qualitative_device_level_relative_ordering_only";

cfg.phase13A.constitutiveModelSpecificationFile = fullfile(cfg.outputDir, ...
    'phase13A_constitutive_model_specification.csv');
cfg.phase13A.parameterRoleLedgerFile = fullfile(cfg.outputDir, ...
    'phase13A_parameter_role_ledger.csv');
cfg.phase13A.globalParameterPriorsFile = fullfile(cfg.outputDir, ...
    'phase13A_global_parameter_priors.csv');
cfg.phase13A.mechanicalToTcMappingFile = fullfile(cfg.outputDir, ...
    'phase13A_mechanical_to_Tc_mapping.csv');
cfg.phase13A.mechanicalToConnectivityMappingFile = fullfile(cfg.outputDir, ...
    'phase13A_mechanical_to_connectivity_mapping.csv');
cfg.phase13A.normalStateModelSpecificationFile = fullfile(cfg.outputDir, ...
    'phase13A_normal_state_model_specification.csv');
cfg.phase13A.disorderModelSpecificationFile = fullfile(cfg.outputDir, ...
    'phase13A_disorder_model_specification.csv');
cfg.phase13A.prohibitedFlexibilityLedgerFile = fullfile(cfg.outputDir, ...
    'phase13A_prohibited_flexibility_ledger.csv');
cfg.phase13A.calibrationHoldoutPlanFile = fullfile(cfg.outputDir, ...
    'phase13A_calibration_holdout_plan.csv');
cfg.phase13A.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13A_gate_summary.csv');
cfg.phase13A.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13A_handoff_status.csv');
cfg.phase13A.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13A_source_provenance_checkpoint.csv');
cfg.phase13A.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13A_constitutive_mapping_summary');
cfg.phase13A.description = ...
    'Constitutive transport mapping freeze';
cfg.phase13A.allowRamanTransportFit = false;
cfg.phase13A.allowDeviceSpecificMechanismParameters = false;
cfg.phase13A.allowPhase6LabelsAsTargets = false;
cfg.phase13A.allowTransportRetuningDuringFreeze = false;
cfg.phase13A.fullTransportRecomputationRequired = true;
cfg.phase13A.localTcMechanicalInputs = [ ...
    "coverage_transfer"; "through_thickness_attenuation" ...
    ];
cfg.phase13A.connectivityMechanicalInputs = [ ...
    "boundary_gradient"; "crack_relaxation"; "coverage_transfer" ...
    ];
cfg.phase13A.calibrationMode = "leave_one_device_out_shared_parameters";
cfg.phase13A.nextPhase = "phase13B_limiting_case_verification";

cfg.phase13B.limitingCaseSpecificationFile = fullfile(cfg.outputDir, ...
    'phase13B_limiting_case_specification.csv');
cfg.phase13B.syntheticProxyResponseFile = fullfile(cfg.outputDir, ...
    'phase13B_synthetic_proxy_response.csv');
cfg.phase13B.deviceExpectedBehaviorFile = fullfile(cfg.outputDir, ...
    'phase13B_device_expected_behavior.csv');
cfg.phase13B.componentAblationSummaryFile = fullfile(cfg.outputDir, ...
    'phase13B_component_ablation_summary.csv');
cfg.phase13B.monotonicityChecksFile = fullfile(cfg.outputDir, ...
    'phase13B_monotonicity_checks.csv');
cfg.phase13B.calibrationFirewallFile = fullfile(cfg.outputDir, ...
    'phase13B_calibration_firewall.csv');
cfg.phase13B.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13B_gate_summary.csv');
cfg.phase13B.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13B_handoff_status.csv');
cfg.phase13B.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13B_source_provenance_checkpoint.csv');
cfg.phase13B.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13B_limiting_case_summary');
cfg.phase13B.description = ...
    'Limiting-case and component-ablation verification';
cfg.phase13B.allowExperimentalResidualUse = false;
cfg.phase13B.allowParameterRetuning = false;
cfg.phase13B.allowTransportRelabeling = false;
cfg.phase13B.minimumMonotonicityPassFraction = 1.0;
cfg.phase13B.nextPhase = "phase13C_shared_RT_calibration";

cfg.phase13C.RTDataLockManifestFile = fullfile(cfg.outputDir, ...
    'phase13C_RT_data_lock_manifest.csv');
cfg.phase13C.calibrationObjectiveSpecificationFile = fullfile(cfg.outputDir, ...
    'phase13C_calibration_objective_specification.csv');
cfg.phase13C.parameterFitManifestFile = fullfile(cfg.outputDir, ...
    'phase13C_parameter_fit_manifest.csv');
cfg.phase13C.leaveOneDeviceOutManifestFile = fullfile(cfg.outputDir, ...
    'phase13C_leave_one_device_out_manifest.csv');
cfg.phase13C.foldParameterResultsFile = fullfile(cfg.outputDir, ...
    'phase13C_fold_parameter_results.csv');
cfg.phase13C.deviceRTPredictionsFile = fullfile(cfg.outputDir, ...
    'phase13C_device_RT_predictions.csv');
cfg.phase13C.transitionMetricPredictionsFile = fullfile(cfg.outputDir, ...
    'phase13C_transition_metric_predictions.csv');
cfg.phase13C.fullCurveResidualsFile = fullfile(cfg.outputDir, ...
    'phase13C_full_curve_residuals.csv');
cfg.phase13C.probePairPredictionsFile = fullfile(cfg.outputDir, ...
    'phase13C_probe_pair_predictions.csv');
cfg.phase13C.geometryFamilyHoldoutResultsFile = fullfile(cfg.outputDir, ...
    'phase13C_geometry_family_holdout_results.csv');
cfg.phase13C.uncertaintyEnsembleSummaryFile = fullfile(cfg.outputDir, ...
    'phase13C_uncertainty_ensemble_summary.csv');
cfg.phase13C.calibrationFirewallFile = fullfile(cfg.outputDir, ...
    'phase13C_calibration_firewall.csv');
cfg.phase13C.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13C_gate_summary.csv');
cfg.phase13C.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13C_handoff_status.csv');
cfg.phase13C.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13C_source_provenance_checkpoint.csv');
cfg.phase13C.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13C_shared_RT_calibration_summary');
cfg.phase13C.description = ...
    'Phase 13C.1 RT data, objective, fold, and firewall lock';
cfg.phase13C.allowDeviceSpecificMechanismParameters = false;
cfg.phase13C.allowConstitutiveFormRetuning = false;
cfg.phase13C.allowPhase6LabelsAsTargets = false;
cfg.phase13C.allowRamanTransportTargets = false;
cfg.phase13C.allowProbeIndependentRefit = false;
cfg.phase13C.allowAutomaticProbeFallback = false;
cfg.phase13C.predictionExecutionStatus = "not_run_pending_full_RT_solver";
cfg.phase13C.objectiveMetric = [
    "full_curve_normalized_residual"
    "T90"
    "T50"
    "T10"
    "width_T90_T10"
    "low_temperature_residual_fraction"
    "probe_asymmetry"
    ];
cfg.phase13C.objectiveWeight = [0.30; 0.12; 0.12; 0.12; 0.12; 0.12; 0.10];
cfg.phase13C.seedEnsemble = (2001:2030).';
cfg.phase13C.nextPhase = "phase13C_full_RT_prediction_execution";

cfg.phase13C2.fullRTExecutionManifestFile = fullfile(cfg.outputDir, ...
    'phase13C_full_RT_execution_manifest.csv');
cfg.phase13C2.foldTrainingManifestFile = fullfile(cfg.outputDir, ...
    'phase13C_fold_training_manifest.csv');
cfg.phase13C2.foldParameterResultsFile = cfg.phase13C.foldParameterResultsFile;
cfg.phase13C2.sharedParameterSummaryFile = fullfile(cfg.outputDir, ...
    'phase13C_shared_parameter_summary.csv');
cfg.phase13C2.deviceRTPredictionsFile = cfg.phase13C.deviceRTPredictionsFile;
cfg.phase13C2.transitionMetricPredictionsFile = ...
    cfg.phase13C.transitionMetricPredictionsFile;
cfg.phase13C2.fullCurveResidualsFile = cfg.phase13C.fullCurveResidualsFile;
cfg.phase13C2.probePairPredictionsFile = cfg.phase13C.probePairPredictionsFile;
cfg.phase13C2.geometryFamilyHoldoutResultsFile = ...
    cfg.phase13C.geometryFamilyHoldoutResultsFile;
cfg.phase13C2.uncertaintyEnsembleSummaryFile = ...
    cfg.phase13C.uncertaintyEnsembleSummaryFile;
cfg.phase13C2.failedPredictionLogFile = fullfile(cfg.outputDir, ...
    'phase13C_failed_prediction_log.csv');
cfg.phase13C2.solverDiagnosticsFile = fullfile(cfg.outputDir, ...
    'phase13C_solver_diagnostics.csv');
cfg.phase13C2.executionGateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13C_execution_gate_summary.csv');
cfg.phase13C2.executionHandoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13C_execution_handoff_status.csv');
cfg.phase13C2.executionSourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13C_execution_source_provenance.csv');
cfg.phase13C2.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13C_full_RT_execution_summary');
cfg.phase13C2.description = ...
    'Full shared R(T) calibration and held-out prediction execution';
cfg.phase13C2.candidateCount = 13;
cfg.phase13C2.maxTemperaturePoints = 120;
cfg.phase13C2.temperatureGrid_K = linspace(0.05, 2.20, 120).';
cfg.phase13C2.primaryPredictionType = "heldout_LODO_prediction";
cfg.phase13C2.trainingPredictionType = "calibration_prediction";
cfg.phase13C2.geometryPredictionType = "geometry_family_holdout_prediction";
cfg.phase13C2.missingProbePolicy = ...
    "probe_asymmetry_not_applicable_and_available_weights_renormalized";
cfg.phase13C2.predictiveAdequacyDecision = "deferred_to_phase13D";
cfg.phase13C2.nextPhase = "phase13D_predictive_adequacy";

cfg.phase13D.executionValidityFile = fullfile(cfg.outputDir, ...
    'phase13D_execution_validity.csv');
cfg.phase13D.fullCurveAdequacyFile = fullfile(cfg.outputDir, ...
    'phase13D_full_curve_adequacy.csv');
cfg.phase13D.transitionCrossingStatusFile = fullfile(cfg.outputDir, ...
    'phase13D_transition_crossing_status.csv');
cfg.phase13D.transitionCrossingConfusionFile = fullfile(cfg.outputDir, ...
    'phase13D_transition_crossing_confusion.csv');
cfg.phase13D.pairedProbeAdequacyFile = fullfile(cfg.outputDir, ...
    'phase13D_paired_probe_adequacy.csv');
cfg.phase13D.geometryFamilyAdequacyFile = fullfile(cfg.outputDir, ...
    'phase13D_geometry_family_adequacy.csv');
cfg.phase13D.uncertaintyCoverageFile = fullfile(cfg.outputDir, ...
    'phase13D_uncertainty_coverage.csv');
cfg.phase13D.predictiveAdequacyDecisionFile = fullfile(cfg.outputDir, ...
    'phase13D_predictive_adequacy_decision.csv');
cfg.phase13D.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13D_gate_summary.csv');
cfg.phase13D.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13D_handoff_status.csv');
cfg.phase13D.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13D_source_provenance_checkpoint.csv');
cfg.phase13D.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13D_predictive_adequacy_summary');
cfg.phase13D.description = ...
    'Read-only predictive adequacy assessment of frozen Phase 13C.2 outputs';
cfg.phase13D.allowOptimizerRerun = false;
cfg.phase13D.allowConstitutiveRetuning = false;
cfg.phase13D.allowDeviceRelabeling = false;
cfg.phase13D.fullCurveStrongResidualThreshold = 0.35;
cfg.phase13D.fullCurvePartialResidualThreshold = 0.65;
cfg.phase13D.familyAdequacyResidualThreshold = 0.50;
cfg.phase13D.transitionThresholds = [0.90; 0.50; 0.10];
cfg.phase13D.transitionThresholdNames = ["T90"; "T50"; "T10"];
cfg.phase13D.minimumCoverageTarget = 0.68;
cfg.phase13D.predictiveAdequacyPassResidualThreshold = 0.50;
cfg.phase13D.predictiveAdequacyPassFractionTarget = 0.67;
cfg.phase13D.nextPhase = "phase13E_or_model_revision_decision";

cfg.phase13E.deviceFailureDecompositionFile = fullfile(cfg.outputDir, ...
    'phase13E_device_failure_decomposition.csv');
cfg.phase13E.temperatureRegionResidualsFile = fullfile(cfg.outputDir, ...
    'phase13E_temperature_region_residuals.csv');
cfg.phase13E.thresholdCrossingFailureLedgerFile = fullfile(cfg.outputDir, ...
    'phase13E_threshold_crossing_failure_ledger.csv');
cfg.phase13E.probeAsymmetryFailureLedgerFile = fullfile(cfg.outputDir, ...
    'phase13E_probe_asymmetry_failure_ledger.csv');
cfg.phase13E.missingInputLedgerFile = fullfile(cfg.outputDir, ...
    'phase13E_missing_input_ledger.csv');
cfg.phase13E.modelLayerDiagnosisFile = fullfile(cfg.outputDir, ...
    'phase13E_model_layer_diagnosis.csv');
cfg.phase13E.candidateUpgradeRankingFile = fullfile(cfg.outputDir, ...
    'phase13E_candidate_upgrade_ranking.csv');
cfg.phase13E.selectedUpgradeScopeFile = fullfile(cfg.outputDir, ...
    'phase13E_selected_upgrade_scope.csv');
cfg.phase13E.prohibitedFlexibilityLedgerFile = fullfile(cfg.outputDir, ...
    'phase13E_prohibited_flexibility_ledger.csv');
cfg.phase13E.claimUpdateFile = fullfile(cfg.outputDir, ...
    'phase13E_claim_update.csv');
cfg.phase13E.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13E_gate_summary.csv');
cfg.phase13E.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13E_handoff_status.csv');
cfg.phase13E.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13E_source_provenance_checkpoint.csv');
cfg.phase13E.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13E_missing_input_model_adequacy_audit');
cfg.phase13E.description = ...
    'Read-only missing-input and model-adequacy audit after Phase 13D';
cfg.phase13E.allowOptimizerRerun = false;
cfg.phase13E.allowConstitutiveRetuning = false;
cfg.phase13E.allowDeviceSpecificFitting = false;
cfg.phase13E.allowTransportRelabeling = false;
cfg.phase13E.temperatureRegionNames = [
    "lowT"
    "transition"
    "onset"
    "normal"
    ];
cfg.phase13E.temperatureRegionEdges = [0.00 0.25 0.60 0.85 1.00];
cfg.phase13E.maxSelectedUpgradeCount = 2;
cfg.phase13E.nextPhase = "bounded_phase14_nonlinear_transport";

cfg.phase13F.upgradeModelSpecificationFile = fullfile(cfg.outputDir, ...
    'phase13F_upgrade_model_specification.csv');
cfg.phase13F.parameterRoleLedgerFile = fullfile(cfg.outputDir, ...
    'phase13F_parameter_role_ledger.csv');
cfg.phase13F.baselineWindowManifestFile = fullfile(cfg.outputDir, ...
    'phase13F_baseline_window_manifest.csv');
cfg.phase13F.residualShuntSpecificationFile = fullfile(cfg.outputDir, ...
    'phase13F_residual_shunt_specification.csv');
cfg.phase13F.interfaceTransferInputLedgerFile = fullfile(cfg.outputDir, ...
    'phase13F_interface_transfer_input_ledger.csv');
cfg.phase13F.prohibitedFlexibilityLedgerFile = fullfile(cfg.outputDir, ...
    'phase13F_prohibited_flexibility_ledger.csv');
cfg.phase13F.comparisonThresholdsFile = fullfile(cfg.outputDir, ...
    'phase13F_comparison_thresholds.csv');
cfg.phase13F.variantManifestFile = fullfile(cfg.outputDir, ...
    'phase13F_variant_manifest.csv');
cfg.phase13F.specificationGateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13F_specification_gate_summary.csv');
cfg.phase13F.specificationHandoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13F_specification_handoff_status.csv');
cfg.phase13F.inputResolutionFile = fullfile(cfg.outputDir, ...
    'phase13F_input_resolution_ledger.csv');
cfg.phase13F.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13F_source_provenance_checkpoint.csv');
cfg.phase13F.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13F_upgrade_specification_freeze');
cfg.phase13F.description = ...
    'Constrained R(T) model revision specification freeze';
cfg.phase13F.allowOptimizerRerunInSpec = false;
cfg.phase13F.allowDeviceSpecificTcGain = false;
cfg.phase13F.allowDeviceSpecificBoundaryCoefficient = false;
cfg.phase13F.allowDeviceSpecificCrackCoefficient = false;
cfg.phase13F.allowRamanFitting = false;
cfg.phase13F.allowUnrestrictedSpatialDisorder = false;
cfg.phase13F.allowPhaseDynamics = false;
cfg.phase13F.allowElectrothermalFeedback = false;
cfg.phase13F.variantIds = ["F0"; "FB"; "FI"; "FBI"];
cfg.phase13F.normalStateWindowScaled = [0.85 1.00];
cfg.phase13F.materialMedianResidualImprovement = 0.10;
cfg.phase13F.minimumImprovedPrimaryDevices = 4;
cfg.phase13F.maximumSevereRegression = 0.05;
cfg.phase13F.minimumCrossingRecoveryGain = 1;
cfg.phase13F.minimumCoverageGain = 0.10;
cfg.phase13F.maxPinnedParameterFoldFraction = 0.50;
cfg.phase13F.nextPhase = "phase13F2_limiting_cases_and_ablations";

cfg.phase13F2.limitingCaseManifestFile = fullfile(cfg.outputDir, ...
    'phase13F2_limiting_case_manifest.csv');
cfg.phase13F2.variantResponseSummaryFile = fullfile(cfg.outputDir, ...
    'phase13F2_variant_response_summary.csv');
cfg.phase13F2.ablationVerificationFile = fullfile(cfg.outputDir, ...
    'phase13F2_ablation_verification.csv');
cfg.phase13F2.identifiabilityChecksFile = fullfile(cfg.outputDir, ...
    'phase13F2_identifiability_checks.csv');
cfg.phase13F2.numericalSanityChecksFile = fullfile(cfg.outputDir, ...
    'phase13F2_numerical_sanity_checks.csv');
cfg.phase13F2.calibrationFirewallFile = fullfile(cfg.outputDir, ...
    'phase13F2_calibration_firewall.csv');
cfg.phase13F2.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13F2_gate_summary.csv');
cfg.phase13F2.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13F2_handoff_status.csv');
cfg.phase13F2.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13F2_source_provenance_checkpoint.csv');
cfg.phase13F2.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13F2_limiting_case_ablation_summary');
cfg.phase13F2.description = ...
    'Pre-fit limiting-case and ablation verification of frozen Phase 13F variants';
cfg.phase13F2.allowExperimentalResidualUse = false;
cfg.phase13F2.allowOptimizerRerun = false;
cfg.phase13F2.allowVariantRetuning = false;
cfg.phase13F2.allowDeviceSpecificFitting = false;
cfg.phase13F2.allowTransportRelabeling = false;
cfg.phase13F2.normalizedTemperatureGrid = linspace(0, 1, 101).';
cfg.phase13F2.minimumResponseSeparation = 0.02;
cfg.phase13F2.maximumVariantCancellation = 0.01;
cfg.phase13F2.minimumMonotonicPassFraction = 1.00;
cfg.phase13F2.minimumAblationPassFraction = 1.00;
cfg.phase13F2.nextPhase = "phase13F3_full_LODO_RT_execution";

cfg.phase13F3.executionManifestFile = fullfile(cfg.outputDir, ...
    'phase13F3_execution_manifest.csv');
cfg.phase13F3.foldTrainingManifestFile = fullfile(cfg.outputDir, ...
    'phase13F3_fold_training_manifest.csv');
cfg.phase13F3.variantFoldParametersFile = fullfile(cfg.outputDir, ...
    'phase13F3_variant_fold_parameters.csv');
cfg.phase13F3.deviceRTPredictionsFile = fullfile(cfg.outputDir, ...
    'phase13F3_device_RT_predictions.csv');
cfg.phase13F3.variantCurveResidualsFile = fullfile(cfg.outputDir, ...
    'phase13F3_variant_curve_residuals.csv');
cfg.phase13F3.transitionMetricResultsFile = fullfile(cfg.outputDir, ...
    'phase13F3_transition_metric_results.csv');
cfg.phase13F3.thresholdCrossingStatusFile = fullfile(cfg.outputDir, ...
    'phase13F3_threshold_crossing_status.csv');
cfg.phase13F3.probePairPredictionsFile = fullfile(cfg.outputDir, ...
    'phase13F3_probe_pair_predictions.csv');
cfg.phase13F3.geometryFamilyHoldoutsFile = fullfile(cfg.outputDir, ...
    'phase13F3_geometry_family_holdouts.csv');
cfg.phase13F3.uncertaintyCoverageFile = fullfile(cfg.outputDir, ...
    'phase13F3_uncertainty_coverage.csv');
cfg.phase13F3.parameterBoundDiagnosticsFile = fullfile(cfg.outputDir, ...
    'phase13F3_parameter_bound_diagnostics.csv');
cfg.phase13F3.variantComparisonFile = fullfile(cfg.outputDir, ...
    'phase13F3_variant_comparison.csv');
cfg.phase13F3.failedPredictionLogFile = fullfile(cfg.outputDir, ...
    'phase13F3_failed_prediction_log.csv');
cfg.phase13F3.solverDiagnosticsFile = fullfile(cfg.outputDir, ...
    'phase13F3_solver_diagnostics.csv');
cfg.phase13F3.executionGateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13F3_execution_gate_summary.csv');
cfg.phase13F3.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13F3_handoff_status.csv');
cfg.phase13F3.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13F3_source_provenance.csv');
cfg.phase13F3.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13F3_full_variant_LODO_execution_summary');
cfg.phase13F3.description = ...
    'Repeated full R(T) LODO execution for four frozen Phase 13F variants';
cfg.phase13F3.expectedPrimaryFoldVariantCount = 24;
cfg.phase13F3.allowVariantRetuning = false;
cfg.phase13F3.allowDeviceSpecificMechanismParameters = false;
cfg.phase13F3.allowRamanTargets = false;
cfg.phase13F3.allowPhase6Targets = false;
cfg.phase13F3.allowTransportRelabeling = false;
cfg.phase13F3.allowAutomaticProbeFallback = false;
cfg.phase13F3.comparativeAdequacyDecision = ...
    "pending_phase13F4";
cfg.phase13F3.nextPhase = "phase13F4_comparative_adequacy_decision";

cfg.phase13F4.variantAdequacySummaryFile = fullfile(cfg.outputDir, ...
    'phase13F4_variant_adequacy_summary.csv');
cfg.phase13F4.upgradeSupportDecisionFile = fullfile(cfg.outputDir, ...
    'phase13F4_upgrade_support_decision.csv');
cfg.phase13F4.parsimonyDecisionFile = fullfile(cfg.outputDir, ...
    'phase13F4_parsimony_decision.csv');
cfg.phase13F4.claimUpdateFile = fullfile(cfg.outputDir, ...
    'phase13F4_claim_update.csv');
cfg.phase13F4.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase13F4_gate_summary.csv');
cfg.phase13F4.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase13F4_handoff_status.csv');
cfg.phase13F4.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase13F4_source_provenance.csv');
cfg.phase13F4.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase13F4_comparative_adequacy_decision_summary');
cfg.phase13F4.description = ...
    'Read-only comparative adequacy decision for Phase 13F variants';
cfg.phase13F4.allowOptimizerRerun = false;
cfg.phase13F4.allowVariantRetuning = false;
cfg.phase13F4.allowDeviceSpecificMechanismParameters = false;
cfg.phase13F4.allowRamanTargets = false;
cfg.phase13F4.allowPhase6Targets = false;
cfg.phase13F4.allowTransportRelabeling = false;
cfg.phase13F4.allowAutomaticProbeFallback = false;
cfg.phase13F4.minimumSelectedDeviceImprovement = ...
    cfg.phase13F.minimumImprovedPrimaryDevices;
cfg.phase13F4.materialMedianImprovementThreshold = ...
    cfg.phase13F.materialMedianResidualImprovement;
cfg.phase13F4.maximumSevereRegression = ...
    cfg.phase13F.maximumSevereRegression;
cfg.phase13F4.minimumCrossingRecoveryGain = ...
    cfg.phase13F.minimumCrossingRecoveryGain;
cfg.phase13F4.minimumCoverageGain = ...
    cfg.phase13F.minimumCoverageGain;
cfg.phase13F4.combinedExtraBenefitThreshold = 0.01;
cfg.phase13F4.expectedPreferredVariant = "FB";
cfg.phase13F4.nextPhase = "phase14_nonlinear_transport_feasibility";

cfg.phase14A.nonlinearDataManifestFile = fullfile(cfg.outputDir, ...
    'phase14A_nonlinear_data_manifest.csv');
cfg.phase14A.observableDefinitionFile = fullfile(cfg.outputDir, ...
    'phase14A_observable_definition.csv');
cfg.phase14A.probeAndSweepLockFile = fullfile(cfg.outputDir, ...
    'phase14A_probe_and_sweep_lock.csv');
cfg.phase14A.objectiveSpecificationFile = fullfile(cfg.outputDir, ...
    'phase14A_objective_specification.csv');
cfg.phase14A.calibrationHoldoutManifestFile = fullfile(cfg.outputDir, ...
    'phase14A_calibration_holdout_manifest.csv');
cfg.phase14A.prohibitedFlexibilityLedgerFile = fullfile(cfg.outputDir, ...
    'phase14A_prohibited_flexibility_ledger.csv');
cfg.phase14A.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase14A_gate_summary.csv');
cfg.phase14A.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase14A_handoff_status.csv');
cfg.phase14A.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase14A_source_provenance.csv');
cfg.phase14A.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase14A_nonlinear_data_objective_lock_summary');
cfg.phase14A.description = ...
    'Nonlinear data availability and objective lock before current switching';
cfg.phase14A.equilibriumBaseline = "FB";
cfg.phase14A.equilibriumRTStatus = "partial_predictive_scope";
cfg.phase14A.sharedQuantitativeRTPredictor = false;
cfg.phase14A.interfaceTransferTerm = "not_identifiable";
cfg.phase14A.focusObservable = "dVdI_I_T";
cfg.phase14A.excludeFieldOscillations = true;
cfg.phase14A.allowOptimizerRerun = false;
cfg.phase14A.allowEquilibriumRetuning = false;
cfg.phase14A.allowDeviceRelabeling = false;
cfg.phase14A.allowPhase6Targets = false;
cfg.phase14A.allowRamanTargets = false;
cfg.phase14A.allowDeviceSpecificIcGain = false;
cfg.phase14A.allowElectrothermalTerms = false;
cfg.phase14A.nextPhase = "phase14B_current_switching_feasibility";

cfg.phase14B.currentModelSpecificationFile = fullfile(cfg.outputDir, ...
    'phase14B_current_model_specification.csv');
cfg.phase14B.parameterRoleLedgerFile = fullfile(cfg.outputDir, ...
    'phase14B_parameter_role_ledger.csv');
cfg.phase14B.solverSpecificationFile = fullfile(cfg.outputDir, ...
    'phase14B_solver_specification.csv');
cfg.phase14B.prohibitedFlexibilityLedgerFile = fullfile(cfg.outputDir, ...
    'phase14B_prohibited_flexibility_ledger.csv');
cfg.phase14B.limitingCasePlanFile = fullfile(cfg.outputDir, ...
    'phase14B_limiting_case_plan.csv');
cfg.phase14B.trainingHoldoutManifestFile = fullfile(cfg.outputDir, ...
    'phase14B_training_holdout_manifest.csv');
cfg.phase14B.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase14B_gate_summary.csv');
cfg.phase14B.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase14B_handoff_status.csv');
cfg.phase14B.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase14B_source_provenance.csv');
cfg.phase14B.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase14B_current_model_solver_freeze_summary');
cfg.phase14B.description = ...
    'Current-dependent network model and solver freeze before nonlinear execution';
cfg.phase14B.equilibriumBaseline = "FB";
cfg.phase14B.currentModelVariant = "NI";
cfg.phase14B.baselineModelVariant = "N0";
cfg.phase14B.criticalCurrentLaw = ...
    "Ic_ij(T)=Ic0_ij*(1-(T/Tc_ij)^p)^q for T<Tc_ij; Ic_ij=0 otherwise";
cfg.phase14B.Ic0CouplingRule = ...
    "Ic0_ij=global_Ic_scale*g(W_ij,Tc_ij,Rn_ij)";
cfg.phase14B.differentialResistanceScheme = ...
    "central_finite_difference_on_frozen_current_grid";
cfg.phase14B.currentSteppingDirection = "positive_and_negative_separate";
cfg.phase14B.allowedSolverStatuses = [
    "converged"
    "maximum_iterations_reached"
    "state_cycle_detected"
    "singular_network"
    "invalid_branch_current"
    ];
cfg.phase14B.sharedParameterNames = [
    "global_Ic_scale"
    "shared_temperature_exponent_p"
    "shared_temperature_exponent_q"
    "shared_switching_width"
    "shared_iteration_tolerance"
    "shared_dissipative_state_resistance"
    ];
cfg.phase14B.phase14BCandidateDevices = ["AS001"; "AS004"];
cfg.phase14B.phase15DeferredDevices = "AS006";
cfg.phase14B.allowEquilibriumRetuning = false;
cfg.phase14B.allowDeviceSpecificIcScale = false;
cfg.phase14B.allowDeviceSpecificSwitchingExponents = false;
cfg.phase14B.allowManualSwitchingCurrents = false;
cfg.phase14B.allowThermalFeedback = false;
cfg.phase14B.allowPhaseDynamics = false;
cfg.phase14B.allowFieldPeriodicityTerms = false;
cfg.phase14B.allowRamanTargets = false;
cfg.phase14B.allowPhase6Targets = false;
cfg.phase14B.allowDeviceRelabeling = false;
cfg.phase14B.nextPhase = "phase14B2_synthetic_switching_solver_verification";

cfg.phase14B2.singleLinkSwitchingFile = fullfile(cfg.outputDir, ...
    'phase14B2_single_link_switching.csv');
cfg.phase14B2.parallelPathRedistributionFile = fullfile(cfg.outputDir, ...
    'phase14B2_parallel_path_redistribution.csv');
cfg.phase14B2.boundaryBottleneckResultsFile = fullfile(cfg.outputDir, ...
    'phase14B2_boundary_bottleneck_results.csv');
cfg.phase14B2.currentSymmetryChecksFile = fullfile(cfg.outputDir, ...
    'phase14B2_current_symmetry_checks.csv');
cfg.phase14B2.IcTemperatureMonotonicityFile = fullfile(cfg.outputDir, ...
    'phase14B2_Ic_temperature_monotonicity.csv');
cfg.phase14B2.highCurrentLimitFile = fullfile(cfg.outputDir, ...
    'phase14B2_high_current_limit.csv');
cfg.phase14B2.zeroCurrentFBRecoveryFile = fullfile(cfg.outputDir, ...
    'phase14B2_zero_current_FB_recovery.csv');
cfg.phase14B2.solverConvergenceFile = fullfile(cfg.outputDir, ...
    'phase14B2_solver_convergence.csv');
cfg.phase14B2.stateCycleLogFile = fullfile(cfg.outputDir, ...
    'phase14B2_state_cycle_log.csv');
cfg.phase14B2.limitingCaseSummaryFile = fullfile(cfg.outputDir, ...
    'phase14B2_limiting_case_summary.csv');
cfg.phase14B2.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase14B2_gate_summary.csv');
cfg.phase14B2.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase14B2_handoff_status.csv');
cfg.phase14B2.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase14B2_source_provenance.csv');
cfg.phase14B2.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase14B2_synthetic_switching_solver_verification_summary');
cfg.phase14B2.description = ...
    'Synthetic switching and solver verification before experimental nonlinear execution';
cfg.phase14B2.currentGrid = (-1.60:0.20:1.60).';
cfg.phase14B2.temperatureGrid = [0.00; 0.25; 0.50; 0.75; 1.00; 1.10];
cfg.phase14B2.monotonicTolerance = 1e-12;
cfg.phase14B2.symmetryTolerance = 1e-10;
cfg.phase14B2.zeroCurrentTolerance = 1e-12;
cfg.phase14B2.highCurrentRelativeTolerance = 0.15;
cfg.phase14B2.maxIterations = 20;
cfg.phase14B2.allowExperimentalResidualInspection = false;
cfg.phase14B2.allowThermalFeedback = false;
cfg.phase14B2.allowPhaseDynamics = false;
cfg.phase14B2.nextPhase = "phase14B3_AS001_AS004_nonlinear_execution";

cfg.phase14B3.executionManifestFile = fullfile(cfg.outputDir, ...
    'phase14B3_execution_manifest.csv');
cfg.phase14B3.rawDataResolutionFile = fullfile(cfg.outputDir, ...
    'phase14B3_raw_data_resolution.csv');
cfg.phase14B3.sharedParameterCalibrationFile = fullfile(cfg.outputDir, ...
    'phase14B3_shared_parameter_calibration.csv');
cfg.phase14B3.temperatureSliceMetricsFile = fullfile(cfg.outputDir, ...
    'phase14B3_temperature_slice_metrics.csv');
cfg.phase14B3.devicePredictionMetricsFile = fullfile(cfg.outputDir, ...
    'phase14B3_device_prediction_metrics.csv');
cfg.phase14B3.switchingFeatureLedgerFile = fullfile(cfg.outputDir, ...
    'phase14B3_switching_feature_ledger.csv');
cfg.phase14B3.N0NIComparisonFile = fullfile(cfg.outputDir, ...
    'phase14B3_N0_NI_comparison.csv');
cfg.phase14B3.currentSymmetryAssessmentFile = fullfile(cfg.outputDir, ...
    'phase14B3_current_symmetry_assessment.csv');
cfg.phase14B3.predictionIntervalCoverageFile = fullfile(cfg.outputDir, ...
    'phase14B3_prediction_interval_coverage.csv');
cfg.phase14B3.failedSwitchingLogFile = fullfile(cfg.outputDir, ...
    'phase14B3_failed_switching_log.csv');
cfg.phase14B3.solverDiagnosticsFile = fullfile(cfg.outputDir, ...
    'phase14B3_solver_diagnostics.csv');
cfg.phase14B3.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase14B3_gate_summary.csv');
cfg.phase14B3.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase14B3_handoff_status.csv');
cfg.phase14B3.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase14B3_source_provenance.csv');
cfg.phase14B3.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase14B3_AS001_AS004_nonlinear_execution_summary');
cfg.phase14B3.description = ...
    'AS001/AS004 held-out nonlinear current-switching execution';
cfg.phase14B3.candidateDevices = ["AS001"; "AS004"];
cfg.phase14B3.comparisonVariants = ["N0"; "NI"];
cfg.phase14B3.trainTemperatureSlices = [0.25; 0.50; 0.75];
cfg.phase14B3.heldoutTemperatureSlices = [0.35; 0.65];
cfg.phase14B3.currentGrid = (-1.40:0.20:1.40).';
cfg.phase14B3.sharedIcScale = 1.00;
cfg.phase14B3.sharedTemperatureExponentP = 2.00;
cfg.phase14B3.sharedTemperatureExponentQ = 1.00;
cfg.phase14B3.sharedSwitchingWidth = 0.08;
cfg.phase14B3.sharedDissipativeResistance = 1.00;
cfg.phase14B3.predictionIntervalHalfWidth = 0.08;
cfg.phase14B3.allowThermalFeedback = false;
cfg.phase14B3.allowPhaseDynamics = false;
cfg.phase14B3.allowFieldDependentData = false;
cfg.phase14B3.allowRamanTargets = false;
cfg.phase14B3.allowDeviceSpecificNonlinearParameters = false;
cfg.phase14B3.allowManualSwitchingCurrents = false;
cfg.phase14B3.allowEquilibriumRetuning = false;
cfg.phase14B3.rawGridPolicy = ...
    'use_locked_raw_grid_when_loader_paths_exist_otherwise_record_proxy_execution_status';
cfg.phase14B3.nextPhase = "phase14B4_raw_nonlinear_data_resolution";

cfg.phase14B4.rawDataLedgerFile = fullfile(cfg.outputDir, ...
    'phase14B4_raw_nonlinear_data_ledger.csv');
cfg.phase14B4.axisIntegrityFile = fullfile(cfg.outputDir, ...
    'phase14B4_axis_integrity_checks.csv');
cfg.phase14B4.ingestionPolicyFile = fullfile(cfg.outputDir, ...
    'phase14B4_ingestion_policy.csv');
cfg.phase14B4.resolutionDecisionFile = fullfile(cfg.outputDir, ...
    'phase14B4_resolution_decision.csv');
cfg.phase14B4.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase14B4_gate_summary.csv');
cfg.phase14B4.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase14B4_handoff_status.csv');
cfg.phase14B4.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase14B4_source_provenance.csv');
cfg.phase14B4.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase14B4_raw_nonlinear_data_resolution_summary');
cfg.phase14B4.description = ...
    'Raw AS001/AS004 dVdI(I,T) source resolution and ingestion lock';
cfg.phase14B4.candidateDevices = cfg.phase14B3.candidateDevices;
cfg.phase14B4.requiredObservableType = "dVdI_I_T";
cfg.phase14B4.allowedStatusForRawExecution = "raw_data_resolved";
cfg.phase14B4.noProxySubstitution = true;
cfg.phase14B4.allowFitting = false;
cfg.phase14B4.allowSyntheticReplacement = false;
cfg.phase14B4.allowFieldDependentMaps = false;
cfg.phase14B4.currentAxisMonotonicRequired = true;
cfg.phase14B4.zeroCurrentRequired = true;
cfg.phase14B4.requireProbeIdentity = true;
cfg.phase14B4.requireSweepDirection = true;
cfg.phase14B4.requireUnits = true;
cfg.phase14B4.requireFieldCondition = true;
cfg.phase14B4.nextPhaseWhenResolved = "phase14B5_raw_AS001_AS004_nonlinear_prediction_execution";
cfg.phase14B4.nextPhaseWhenUnresolved = "insufficient_raw_data_for_nonlinear_adequacy";

cfg.phase14B4R.candidateSourceLedgerFile = fullfile(cfg.outputDir, ...
    'phase14B4R_candidate_source_ledger.csv');
cfg.phase14B4R.recoveryValidationFile = fullfile(cfg.outputDir, ...
    'phase14B4R_recovery_validation.csv');
cfg.phase14B4R.deviceRecoveryDecisionFile = fullfile(cfg.outputDir, ...
    'phase14B4R_device_recovery_decision.csv');
cfg.phase14B4R.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase14B4R_gate_summary.csv');
cfg.phase14B4R.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase14B4R_handoff_status.csv');
cfg.phase14B4R.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase14B4R_source_provenance.csv');
cfg.phase14B4R.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase14B4R_raw_nonlinear_source_recovery_summary');
cfg.phase14B4R.description = ...
    'Raw nonlinear source recovery for AS001/AS004';
cfg.phase14B4R.candidateDevices = cfg.phase14B4.candidateDevices;
cfg.phase14B4R.deviceRawLabels = table( ...
    ["AS001"; "AS004"], ["ASD088"; "ASD087"], ...
    'VariableNames', {'device', 'raw_label'});
cfg.phase14B4R.deviceMappingSource = ...
    'matlab_sc_network_project_v4/make_experiment_data_table.m and thesis ch4 dimensions note';
cfg.phase14B4R.searchRoots = [
    string(cfg.repoRoot)
    "/Users/asewaket/Documents/Thesis/Raw Transport Data"
    "/Users/asewaket/Documents/Thesis/Raw Transport Data/2023_5_26_ASD087/data"
    ];
cfg.phase14B4R.preferredPatterns = [
    "*%s*dVdIvIvT*.dat"
    "*%s*dVdIvIvT*.csv"
    "*%s*dVdIvIvT*.txt"
    "sm_%s_dVdIvIvT*.mat"
    ];
cfg.phase14B4R.secondaryPatterns = [
    "*%s*dVdIvI*.mat"
    "*%s*dVdIvI*.dat"
    "*%s*dVdIvIvB*.dat"
    "*%s*RvT*.dat"
    ];
cfg.phase14B4R.acceptedMatrixColumns = ["R1"; "R2"; "dVdI"; "R"];
cfg.phase14B4R.acceptedCurrentColumns = ["I"; "current"; "bias_current"];
cfg.phase14B4R.acceptedTemperatureColumns = ["temp"; "T"; "temperature"];
cfg.phase14B4R.allowModelChanges = false;
cfg.phase14B4R.allowFitting = false;
cfg.phase14B4R.allowProxySubstitution = false;
cfg.phase14B4R.figureOnlyAccepted = false;
cfg.phase14B4R.nextPhaseWhenRecovered = "phase14B4_lock_recovered_sources_then_rerun_ingestion";
cfg.phase14B4R.nextPhaseWhenNotRecovered = "phase14D_insufficient_raw_data_decision";

cfg.phase14B4L.rawSourceLockManifestFile = fullfile(cfg.outputDir, ...
    'phase14B4L_raw_source_lock_manifest.csv');
cfg.phase14B4L.fileChecksumManifestFile = fullfile(cfg.outputDir, ...
    'phase14B4L_file_checksum_manifest.csv');
cfg.phase14B4L.loaderSpecificationFile = fullfile(cfg.outputDir, ...
    'phase14B4L_loader_specification.csv');
cfg.phase14B4L.axisValidationFile = fullfile(cfg.outputDir, ...
    'phase14B4L_axis_validation.csv');
cfg.phase14B4L.matrixOrientationValidationFile = fullfile(cfg.outputDir, ...
    'phase14B4L_matrix_orientation_validation.csv');
cfg.phase14B4L.unitsAndMetadataLockFile = fullfile(cfg.outputDir, ...
    'phase14B4L_units_and_metadata_lock.csv');
cfg.phase14B4L.zeroCurrentValidationFile = fullfile(cfg.outputDir, ...
    'phase14B4L_zero_current_validation.csv');
cfg.phase14B4L.duplicateCandidateResolutionFile = fullfile(cfg.outputDir, ...
    'phase14B4L_duplicate_candidate_resolution.csv');
cfg.phase14B4L.canonicalGridManifestFile = fullfile(cfg.outputDir, ...
    'phase14B4L_canonical_grid_manifest.csv');
cfg.phase14B4L.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase14B4L_gate_summary.csv');
cfg.phase14B4L.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase14B4L_handoff_status.csv');
cfg.phase14B4L.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase14B4L_source_provenance.csv');
cfg.phase14B4L.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase14B4L_raw_grid_loader_freeze_summary');
cfg.phase14B4L.canonicalGridDir = fullfile(cfg.outputDir, ...
    'phase14B4L_canonical_grids');
cfg.phase14B4L.description = ...
    'Raw grid parsing, validation, and loader freeze for AS001/AS004';
cfg.phase14B4L.candidateDevices = cfg.phase14B4R.candidateDevices;
cfg.phase14B4L.loaderName = "load_dVdIvIvT_dat";
cfg.phase14B4L.loaderVersion = "v1";
cfg.phase14B4L.requiredColumns = ["temp"; "I"; "R1"; "R2"];
cfg.phase14B4L.primaryMatrixColumn = "R1";
cfg.phase14B4L.secondaryMatrixColumn = "R2";
cfg.phase14B4L.primaryMeasurementChannel = "R1_primary_dVdI";
cfg.phase14B4L.secondaryMeasurementChannel = "R2_secondary_dVdI";
cfg.phase14B4L.measurementChannel = ...
    "R1_primary_dVdI|R2_secondary_dVdI";
cfg.phase14B4L.matrixChannelCount = 2;
cfg.phase14B4L.currentUnits = "A";
cfg.phase14B4L.temperatureUnits = "K";
cfg.phase14B4L.dVdIUnits = "Ohm";
cfg.phase14B4L.field_T = 0;
cfg.phase14B4L.fieldCondition = "zero_field_or_fixed_field_not_field_sweep";
cfg.phase14B4L.sweepDirection = "negative_to_positive_current";
cfg.phase14B4L.probePairPolicy = ...
    'R1 and R2 columns retained; R1 used as primary canonical grid for Phase 14B.5 unless explicitly overridden';
cfg.phase14B4L.backgroundSubtractionPolicy = ...
    'not_detected_in_file_header; table values treated as exported measured dVdI/R columns';
cfg.phase14B4L.rawTransportDataRoot = ...
    "/Users/asewaket/Documents/Thesis/Raw Transport Data";
cfg.phase14B4L.repositoryRelativeRoot = "external_raw_transport";
cfg.phase14B4L.allowFitting = false;
cfg.phase14B4L.allowProxySubstitution = false;
cfg.phase14B4L.allowSourcePromotionWithoutChecksum = false;
cfg.phase14B4L.nextPhaseWhenLocked = "phase14B5_raw_nonlinear_execution";
cfg.phase14B4L.nextPhaseWhenBlocked = "phase14D_insufficient_raw_data_decision";

cfg.phase14B5.executionManifestFile = fullfile(cfg.outputDir, ...
    'phase14B5_execution_manifest.csv');
cfg.phase14B5.rawGridUsageFile = fullfile(cfg.outputDir, ...
    'phase14B5_raw_grid_usage.csv');
cfg.phase14B5.sharedParameterLedgerFile = fullfile(cfg.outputDir, ...
    'phase14B5_shared_parameter_ledger.csv');
cfg.phase14B5.fullMapResidualsFile = fullfile(cfg.outputDir, ...
    'phase14B5_full_map_residuals.csv');
cfg.phase14B5.temperatureSliceResidualsFile = fullfile(cfg.outputDir, ...
    'phase14B5_temperature_slice_residuals.csv');
cfg.phase14B5.channelPerformanceFile = fullfile(cfg.outputDir, ...
    'phase14B5_channel_performance.csv');
cfg.phase14B5.switchingCurrentLedgerFile = fullfile(cfg.outputDir, ...
    'phase14B5_switching_current_ledger.csv');
cfg.phase14B5.switchingWidthFeatureFile = fullfile(cfg.outputDir, ...
    'phase14B5_switching_width_feature_counts.csv');
cfg.phase14B5.currentSymmetryFile = fullfile(cfg.outputDir, ...
    'phase14B5_current_symmetry.csv');
cfg.phase14B5.biasResistanceFile = fullfile(cfg.outputDir, ...
    'phase14B5_bias_resistance_summary.csv');
cfg.phase14B5.currentRangeCensoringFile = fullfile(cfg.outputDir, ...
    'phase14B5_current_range_censoring.csv');
cfg.phase14B5.predictionIntervalCoverageFile = fullfile(cfg.outputDir, ...
    'phase14B5_prediction_interval_coverage.csv');
cfg.phase14B5.solverDiagnosticsFile = fullfile(cfg.outputDir, ...
    'phase14B5_solver_diagnostics.csv');
cfg.phase14B5.predictionBoundsAuditFile = fullfile(cfg.outputDir, ...
    'phase14B5_prediction_bounds_audit.csv');
cfg.phase14B5.thermalTriggerAssessmentFile = fullfile(cfg.outputDir, ...
    'phase14B5_thermal_trigger_assessment.csv');
cfg.phase14B5.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase14B5_gate_summary.csv');
cfg.phase14B5.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase14B5_handoff_status.csv');
cfg.phase14B5.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase14B5_source_provenance.csv');
cfg.phase14B5.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase14B5_raw_current_only_execution_summary');
cfg.phase14B5.description = ...
    'Raw AS001/AS004 N0 versus NI current-only nonlinear execution';
cfg.phase14B5.candidateDevices = cfg.phase14B4L.candidateDevices;
cfg.phase14B5.comparisonVariants = ["N0"; "NI"];
cfg.phase14B5.measurementChannels = ["primary"; "secondary"];
cfg.phase14B5.sharedIc0FractionOfCurrentMax = 0.35;
cfg.phase14B5.sharedTemperatureExponentP = 2.0;
cfg.phase14B5.sharedTemperatureExponentQ = 1.0;
cfg.phase14B5.sharedSwitchingWidthFraction = 0.035;
cfg.phase14B5.predictionIntervalHalfWidth = 0.12;
cfg.phase14B5.partialAdequacyResidualThreshold = 0.35;
cfg.phase14B5.weakTransferResidualThreshold = 0.65;
cfg.phase14B5.currentSymmetryTolerance = 0.10;
cfg.phase14B5.minNIImprovementForTrigger = 0.03;
cfg.phase14B5.hysteresisSpecificResidualThreshold = 0.12;
cfg.phase14B5.allowThermalFeedback = false;
cfg.phase14B5.allowPhaseDynamics = false;
cfg.phase14B5.allowElectrothermalAblation = false;
cfg.phase14B5.allowDeviceSpecificNonlinearParameters = false;
cfg.phase14B5.allowProxySubstitution = false;
cfg.phase14B5.allowEquilibriumRetuning = false;
cfg.phase14B5.nextPhaseWhenThermalTriggered = ...
    "phase14C_electrothermal_feedback_ablation";
cfg.phase14B5.nextPhaseWhenThermalNotTriggered = ...
    "phase14D_current_only_adequacy_decision";

cfg.phase14D.executionValiditySummaryFile = fullfile(cfg.outputDir, ...
    'phase14D_execution_validity_summary.csv');
cfg.phase14D.channelAdequacySummaryFile = fullfile(cfg.outputDir, ...
    'phase14D_channel_adequacy_summary.csv');
cfg.phase14D.relativeImprovementLedgerFile = fullfile(cfg.outputDir, ...
    'phase14D_relative_improvement_ledger.csv');
cfg.phase14D.absoluteResidualAssessmentFile = fullfile(cfg.outputDir, ...
    'phase14D_absolute_residual_assessment.csv');
cfg.phase14D.predictionBoundsAssessmentFile = fullfile(cfg.outputDir, ...
    'phase14D_prediction_bounds_assessment.csv');
cfg.phase14D.switchingFeatureAssessmentFile = fullfile(cfg.outputDir, ...
    'phase14D_switching_feature_assessment.csv');
cfg.phase14D.sharedLawTransferAssessmentFile = fullfile(cfg.outputDir, ...
    'phase14D_shared_law_transfer_assessment.csv');
cfg.phase14D.thermalIdentifiabilityStatusFile = fullfile(cfg.outputDir, ...
    'phase14D_thermal_identifiability_status.csv');
cfg.phase14D.failureModeLedgerFile = fullfile(cfg.outputDir, ...
    'phase14D_failure_mode_ledger.csv');
cfg.phase14D.claimDecisionFile = fullfile(cfg.outputDir, ...
    'phase14D_claim_decision.csv');
cfg.phase14D.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase14D_gate_summary.csv');
cfg.phase14D.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase14D_handoff_status.csv');
cfg.phase14D.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase14D_source_provenance.csv');
cfg.phase14D.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase14D_current_only_adequacy_decision_summary');
cfg.phase14D.description = ...
    'Read-only current-only raw nonlinear adequacy decision';
cfg.phase14D.frozenPhase14B5ArtifactCommit = ...
    "b94ba33";
cfg.phase14D.allowSolverRerun = false;
cfg.phase14D.allowParameterRetuning = false;
cfg.phase14D.allowNormalizationChange = false;
cfg.phase14D.allowPredictionClipping = false;
cfg.phase14D.allowChannelReassignment = false;
cfg.phase14D.allowThermalFeedback = false;
cfg.phase14D.allowEquilibriumReopen = false;
cfg.phase14D.expectedPhase14B5Closure = ...
    "complete_raw_current_switching_execution_with_bounds_limitation";
cfg.phase14D.nextPhase = "phase15_field_dependent_and_phase_aware_transport";

cfg.phase15A.rawFieldSourceLockFile = fullfile(cfg.outputDir, ...
    'phase15A_as006_field_raw_source_lock.csv');
cfg.phase15A.axisMetadataLockFile = fullfile(cfg.outputDir, ...
    'phase15A_as006_field_axis_metadata_lock.csv');
cfg.phase15A.channelLockFile = fullfile(cfg.outputDir, ...
    'phase15A_as006_field_channel_lock.csv');
cfg.phase15A.sweepHistoryAuditFile = fullfile(cfg.outputDir, ...
    'phase15A_as006_field_sweep_history_audit.csv');
cfg.phase15A.phase15PolicyFile = fullfile(cfg.outputDir, ...
    'phase15A_field_model_policy.csv');
cfg.phase15A.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase15A_as006_field_data_lock_gate_summary.csv');
cfg.phase15A.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase15A_as006_field_data_lock_handoff_status.csv');
cfg.phase15A.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase15A_as006_field_source_provenance.csv');
cfg.phase15A.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase15A_as006_field_data_lock_summary');
cfg.phase15A.description = ...
    'AS006 dVdI(I,B,T) raw field-data recovery and observable lock';
cfg.phase15A.device = "AS006";
cfg.phase15A.requiredObservableType = "dVdI_I_B_fixed_T";
cfg.phase15A.rawFieldFile = ...
    "/Users/asewaket/Documents/Thesis/Raw Transport Data/2023_5_26_ASD087/data/ASD092_dVdIvIvB_0108.dat";
cfg.phase15A.rawSourceLabel = "ASD092_dVdIvIvB_0108";
cfg.phase15A.legacyLoaderFile = fullfile(cfg.repoRoot, ...
    'matlab_v7_4_6_files', 'load_v73_experimental_field_dvdi.m');
cfg.phase15A.requiredColumns = ["Bfield"; "I"; "R1"; "R2"];
cfg.phase15A.currentUnits = "A";
cfg.phase15A.fieldUnits = "T";
cfg.phase15A.dVdIUnits = "Ohm";
cfg.phase15A.assumedTemperature_K = 0.06;
cfg.phase15A.fieldDirection = "out_of_plane";
cfg.phase15A.primaryMatrixColumn = "R1";
cfg.phase15A.secondaryMatrixColumn = "R2";
cfg.phase15A.primaryMeasurementChannel = "R1_top_4_10_dVdI";
cfg.phase15A.secondaryMeasurementChannel = "R2_bottom_3_9_dVdI";
cfg.phase15A.requireZeroCurrent = true;
cfg.phase15A.requireZeroField = true;
cfg.phase15A.requireBothChannels = true;
cfg.phase15A.allowPhaseAwareModel = false;
cfg.phase15A.allowPhaseDynamics = false;
cfg.phase15A.allowFluxQuantizationFit = false;
cfg.phase15A.allowTopologicalClaim = false;
cfg.phase15A.allowParameterRetuning = false;
cfg.phase15A.allowRawDataRelabeling = false;
cfg.phase15A.nextPhase = "phase15B_phase_aware_model_specification_freeze";

cfg.phase15B.phaseModelSpecificationFile = fullfile(cfg.outputDir, ...
    'phase15B_phase_model_specification.csv');
cfg.phase15B.modelVariantLedgerFile = fullfile(cfg.outputDir, ...
    'phase15B_model_variant_ledger.csv');
cfg.phase15B.phaseLinkEquationsFile = fullfile(cfg.outputDir, ...
    'phase15B_phase_link_equations.csv');
cfg.phase15B.loopGeometryManifestFile = fullfile(cfg.outputDir, ...
    'phase15B_loop_geometry_manifest.csv');
cfg.phase15B.effectiveAreaPriorFile = fullfile(cfg.outputDir, ...
    'phase15B_effective_area_prior.csv');
cfg.phase15B.fieldSuppressionSpecificationFile = fullfile(cfg.outputDir, ...
    'phase15B_field_suppression_specification.csv');
cfg.phase15B.parameterRoleLedgerFile = fullfile(cfg.outputDir, ...
    'phase15B_parameter_role_ledger.csv');
cfg.phase15B.prohibitedFlexibilityLedgerFile = fullfile(cfg.outputDir, ...
    'phase15B_prohibited_flexibility_ledger.csv');
cfg.phase15B.validationHoldoutPlanFile = fullfile(cfg.outputDir, ...
    'phase15B_validation_holdout_plan.csv');
cfg.phase15B.syntheticTestPlanFile = fullfile(cfg.outputDir, ...
    'phase15B_synthetic_test_plan.csv');
cfg.phase15B.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase15B_gate_summary.csv');
cfg.phase15B.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase15B_handoff_status.csv');
cfg.phase15B.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase15B_source_provenance.csv');
cfg.phase15B.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase15B_phase_aware_specification_summary');
cfg.phase15B.description = ...
    'Minimal phase-aware field-response model specification freeze';
cfg.phase15B.frozenPhase15AArtifactCommit = "0f20cd6";
cfg.phase15B.inheritedEquilibriumBaseline = "FB";
cfg.phase15B.inheritedCurrentSwitchingBaseline = "NI";
cfg.phase15B.sharedQuantitativeRTPredictor = false;
cfg.phase15B.sharedRawNonlinearPredictor = false;
cfg.phase15B.rawAS006ResidualsUsed = false;
cfg.phase15B.manualPeriodFit = false;
cfg.phase15B.topologicalTermUsed = false;
cfg.phase15B.thermalFeedbackUsed = false;
cfg.phase15B.nextPhase = ...
    "phase15C_synthetic_flux_interference_verification";

cfg.phase15C.syntheticExecutionManifestFile = fullfile(cfg.outputDir, ...
    'phase15C_synthetic_execution_manifest.csv');
cfg.phase15C.zeroFieldInheritanceFile = fullfile(cfg.outputDir, ...
    'phase15C_zero_field_inheritance.csv');
cfg.phase15C.singleLinkResultsFile = fullfile(cfg.outputDir, ...
    'phase15C_single_link_results.csv');
cfg.phase15C.twoPathInterferenceFile = fullfile(cfg.outputDir, ...
    'phase15C_two_path_interference.csv');
cfg.phase15C.fluxPeriodicityFile = fullfile(cfg.outputDir, ...
    'phase15C_flux_periodicity.csv');
cfg.phase15C.effectiveAreaScalingFile = fullfile(cfg.outputDir, ...
    'phase15C_effective_area_scaling.csv');
cfg.phase15C.fieldSuppressionResultsFile = fullfile(cfg.outputDir, ...
    'phase15C_field_suppression_results.csv');
cfg.phase15C.phaseAblationResultsFile = fullfile(cfg.outputDir, ...
    'phase15C_phase_ablation_results.csv');
cfg.phase15C.fieldSymmetryFile = fullfile(cfg.outputDir, ...
    'phase15C_field_symmetry.csv');
cfg.phase15C.sharedChannelStateFile = fullfile(cfg.outputDir, ...
    'phase15C_shared_channel_state.csv');
cfg.phase15C.phaseSolverDiagnosticsFile = fullfile(cfg.outputDir, ...
    'phase15C_phase_solver_diagnostics.csv');
cfg.phase15C.fluxStateStabilityFile = fullfile(cfg.outputDir, ...
    'phase15C_flux_state_stability.csv');
cfg.phase15C.failedCaseLogFile = fullfile(cfg.outputDir, ...
    'phase15C_failed_case_log.csv');
cfg.phase15C.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase15C_gate_summary.csv');
cfg.phase15C.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase15C_handoff_status.csv');
cfg.phase15C.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase15C_source_provenance.csv');
cfg.phase15C.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase15C_synthetic_flux_interference_summary');
cfg.phase15C.description = ...
    'Synthetic flux and phase-interference verification';
cfg.phase15C.frozenPhase15BArtifactCommit = "30cd2d8";
cfg.phase15C.phaseSolverType = "static_constrained";
cfg.phase15C.dynamicPhaseSlipsModeled = false;
cfg.phase15C.syntheticPhi0_Wb = 2.067833848e-15;
cfg.phase15C.syntheticAreaA_m2 = 2.0e-12;
cfg.phase15C.syntheticAreaScale = 2.0;
cfg.phase15C.fieldSuppressionB0_T = 8.0e-3;
cfg.phase15C.tolerance = 1e-9;
cfg.phase15C.noAS006ResidualsInspected = true;
cfg.phase15C.noFittedOscillationPeriod = true;
cfg.phase15C.noTopologicalTerm = true;
cfg.phase15C.noThermalTerm = true;
cfg.phase15C.nextPhase = "phase15D_raw_AS006_field_execution";

cfg.phase15D.executionManifestFile = fullfile(cfg.outputDir, ...
    'phase15D_raw_AS006_field_execution_manifest.csv');
cfg.phase15D.variantResidualsFile = fullfile(cfg.outputDir, ...
    'phase15D_variant_full_map_residuals.csv');
cfg.phase15D.heldoutFieldWindowFile = fullfile(cfg.outputDir, ...
    'phase15D_heldout_field_window_residuals.csv');
cfg.phase15D.currentRangeTransferFile = fullfile(cfg.outputDir, ...
    'phase15D_current_range_transfer.csv');
cfg.phase15D.fieldSymmetryFile = fullfile(cfg.outputDir, ...
    'phase15D_field_symmetry.csv');
cfg.phase15D.criticalCurrentEnvelopeFile = fullfile(cfg.outputDir, ...
    'phase15D_critical_current_envelopes.csv');
cfg.phase15D.oscillatoryStructureFile = fullfile(cfg.outputDir, ...
    'phase15D_oscillatory_structure.csv');
cfg.phase15D.zeroFieldInheritanceFile = fullfile(cfg.outputDir, ...
    'phase15D_zero_field_inheritance.csv');
cfg.phase15D.predictionBoundsAuditFile = fullfile(cfg.outputDir, ...
    'phase15D_prediction_bounds_audit.csv');
cfg.phase15D.sharedPhaseStateFile = fullfile(cfg.outputDir, ...
    'phase15D_shared_phase_state.csv');
cfg.phase15D.channelTransformAuditFile = fullfile(cfg.outputDir, ...
    'phase15D_channel_transform_audit.csv');
cfg.phase15D.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase15D_gate_summary.csv');
cfg.phase15D.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase15D_handoff_status.csv');
cfg.phase15D.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase15D_source_provenance.csv');
cfg.phase15D.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase15D_raw_AS006_field_execution_summary');
cfg.phase15D.description = ...
    'Raw AS006 field-dependent execution for P0/PB/Pphi';
cfg.phase15D.expectedPhase15AClosure = ...
    "pass_as006_field_observable_lock";
cfg.phase15D.expectedPhase15BClosure = ...
    "pass_minimal_phase_aware_model_freeze";
cfg.phase15D.expectedPhase15CClosure = ...
    "pass_synthetic_flux_interference_verification";
cfg.phase15D.variants = ["P0"; "PB"; "Pphi"];
cfg.phase15D.channels = ["R1"; "R2"];
cfg.phase15D.channelRoles = ["primary"; "secondary"];
cfg.phase15D.currentSwitchingIcFraction = 0.32;
cfg.phase15D.currentSwitchingWidthFraction = 0.08;
cfg.phase15D.secondaryChannelScale = 0.92;
cfg.phase15D.centralFieldHalfWindow_T = 0.015;
cfg.phase15D.currentHoldoutFraction = 0.60;
cfg.phase15D.oscillationPeakProminenceFraction = 0.08;
cfg.phase15D.predictionBoundHalfWidth = 0.35;
cfg.phase15D.noManualPeriodFit = true;
cfg.phase15D.noTopologicalTerm = true;
cfg.phase15D.noThermalMemory = true;
cfg.phase15D.noIndependentR1R2LoopParameters = true;
cfg.phase15D.phaseSolverType = cfg.phase15C.phaseSolverType;
cfg.phase15D.syntheticPhi0_Wb = cfg.phase15C.syntheticPhi0_Wb;
cfg.phase15D.effectiveArea_m2 = cfg.phase15C.syntheticAreaA_m2;
cfg.phase15D.fieldSuppressionB0_T = cfg.phase15C.fieldSuppressionB0_T;
cfg.phase15D.nextPhase = "phase15E_field_model_adequacy_decision";

cfg.phase15E.executionValiditySummaryFile = fullfile(cfg.outputDir, ...
    'phase15E_execution_validity_summary.csv');
cfg.phase15E.variantResidualComparisonFile = fullfile(cfg.outputDir, ...
    'phase15E_variant_residual_comparison.csv');
cfg.phase15E.currentRegionAssessmentFile = fullfile(cfg.outputDir, ...
    'phase15E_current_region_assessment.csv');
cfg.phase15E.criticalCurrentEnvelopeAssessmentFile = fullfile(cfg.outputDir, ...
    'phase15E_critical_current_envelope_assessment.csv');
cfg.phase15E.oscillationMorphologyAssessmentFile = fullfile(cfg.outputDir, ...
    'phase15E_oscillation_morphology_assessment.csv');
cfg.phase15E.turningPointComparisonFile = fullfile(cfg.outputDir, ...
    'phase15E_turning_point_comparison.csv');
cfg.phase15E.predictionBoundsAssessmentFile = fullfile(cfg.outputDir, ...
    'phase15E_prediction_bounds_assessment.csv');
cfg.phase15E.channelTransferSummaryFile = fullfile(cfg.outputDir, ...
    'phase15E_channel_transfer_summary.csv');
cfg.phase15E.complexityIdentifiabilityLedgerFile = fullfile(cfg.outputDir, ...
    'phase15E_complexity_identifiability_ledger.csv');
cfg.phase15E.mechanismClaimLedgerFile = fullfile(cfg.outputDir, ...
    'phase15E_mechanism_claim_ledger.csv');
cfg.phase15E.preferredVariantDecisionFile = fullfile(cfg.outputDir, ...
    'phase15E_preferred_variant_decision.csv');
cfg.phase15E.claimDecisionFile = fullfile(cfg.outputDir, ...
    'phase15E_claim_decision.csv');
cfg.phase15E.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase15E_gate_summary.csv');
cfg.phase15E.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase15E_handoff_status.csv');
cfg.phase15E.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase15E_source_provenance.csv');
cfg.phase15E.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase15E_field_model_adequacy_decision_summary');
cfg.phase15E.description = ...
    'Read-only AS006 field-model adequacy decision';
cfg.phase15E.frozenPhase15DArtifactCommit = ...
    "cfb95f1";
cfg.phase15E.expectedPhase15DClosure = ...
    "complete_raw_AS006_field_execution";
cfg.phase15E.expectedPhase15DIntegrity = "pass";
cfg.phase15E.allowSolverRerun = false;
cfg.phase15E.allowParameterRetuning = false;
cfg.phase15E.allowPeriodFit = false;
cfg.phase15E.allowLoopCountReduction = false;
cfg.phase15E.allowTopologyTerm = false;
cfg.phase15E.allowVortexTerm = false;
cfg.phase15E.allowThermalMemory = false;
cfg.phase15E.allowMagneticScreening = false;
cfg.phase15E.allowIndependentR1R2PhaseParameters = false;
cfg.phase15E.modestPphiFractionalGainThreshold = 0.03;
cfg.phase15E.largeTurningPointOverproductionThreshold = 5;
cfg.phase15E.nextPhase = "phase16_joint_identifiability_model_reduction";

cfg.phase16A.globalParameterInventoryFile = fullfile(cfg.outputDir, ...
    'phase16A_global_parameter_inventory.csv');
cfg.phase16A.observableConstraintMatrixFile = fullfile(cfg.outputDir, ...
    'phase16A_observable_constraint_matrix.csv');
cfg.phase16A.recoverabilityMapFile = fullfile(cfg.outputDir, ...
    'phase16A_recoverability_map.csv');
cfg.phase16A.degeneracyLedgerFile = fullfile(cfg.outputDir, ...
    'phase16A_degeneracy_ledger.csv');
cfg.phase16A.modelReductionQueueFile = fullfile(cfg.outputDir, ...
    'phase16A_model_reduction_queue.csv');
cfg.phase16A.frozenInputManifestFile = fullfile(cfg.outputDir, ...
    'phase16A_frozen_input_manifest.csv');
cfg.phase16A.gateSummaryFile = fullfile(cfg.outputDir, ...
    'phase16A_gate_summary.csv');
cfg.phase16A.handoffStatusFile = fullfile(cfg.outputDir, ...
    'phase16A_handoff_status.csv');
cfg.phase16A.sourceProvenanceFile = fullfile(cfg.outputDir, ...
    'phase16A_source_provenance.csv');
cfg.phase16A.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase16A_identifiability_inventory_summary');
cfg.phase16A.description = ...
    'Global latent-quantity inventory and recoverability freeze';
cfg.phase16A.frozenPhase15EArtifactCommit = "127141b";
cfg.phase16A.nextPhase = "phase16B_sensitivity_and_covariance";
cfg.phase16A.noNewMechanism = true;
cfg.phase16A.noParameterRetuning = true;
cfg.phase16A.noSolverRerun = true;

cfg.phase5D.calibrationSeeds = (101:160).';
cfg.phase5D.validationSeeds = (1001:1080).';
cfg.phase5D.boundaryLambdaW = [0 0.02 0.05 0.10 0.20 0.40 0.70 1.00].';
cfg.phase5D.zCriticalGrid = [0.50 0.75 1.0 1.25 1.5 2.0 2.5 3.0].';
cfg.phase5D.nuisancePenaltyWeightGrid = [0.004 0.006 0.008 0.012 0.016].';
cfg.phase5D.nuisancePenaltySensitivitySettings = table( ...
    ["baseline"; "width_regularized"; "shunt_regularized"; ...
    "width_shunt_cross"; "moderate_joint"; "strong_joint"], ...
    [0.004; 0.004; 0.004; 0.004; 0.006; 0.008], ...
    [0.000; 0.020; 0.000; 0.010; 0.020; 0.030], ...
    [0.000; 0.000; 0.020; 0.010; 0.020; 0.030], ...
    [0.000; 0.000; 0.000; 0.020; 0.020; 0.040], ...
    'VariableNames', {'setting_id', 'base_weight', ...
    'width_extra_weight', 'shunt_extra_weight', 'width_shunt_cross_weight'});
cfg.phase5D.caseSigmaResampleCount = 9;
cfg.phase5D.falseStructuredTarget = 0.15;
cfg.phase5D.confidentM0WeakStructuredTarget = 0.15;
cfg.phase5D.strongStructuredDetectionTarget = 0.80;
cfg.phase5D.boundaryUnresolvedTarget = 0.35;
cfg.phase5D.nuisanceBoundaryOccupancyTarget = 0.35;
cfg.phase5D.nuisanceBounds = table( ...
    ["Tc_mean_shift_K"; "Tc_distribution_width_K"; ...
    "residual_normal_shunt"; "normalization_window_shift"; ...
    "temperature_offset_K"; "probe_registration_shift"; ...
    "disorder_amplitude_scale"], ...
    [-0.08; 0.00; 0.00; -0.03; -0.03; -0.06; 0.50], ...
    [0.08; 0.14; 0.10; 0.03; 0.03; 0.06; 1.75], ...
    ["K"; "K"; "normalized_R"; "normalized_R"; "K"; "K"; "scale"], ...
    [0.04; 0.06; 0.04; 0.015; 0.015; 0.03; 0.40], ...
    'VariableNames', {'parameter','lower_bound','upper_bound','units','penalty_scale'});

end
