function cfg = phase5_config(rootDir)
%PHASE5_CONFIG Configuration for the reduced six-device transfer plan.

if nargin < 1 || isempty(rootDir)
    rootDir = fileparts(fileparts(mfilename('fullpath')));
end

repoRoot = fileparts(rootDir);

cfg = struct();
cfg.modelVersion = 'v8.0-phase5';
cfg.device = 'AS006';
cfg.repoRoot = repoRoot;
cfg.rootDir = rootDir;

cfg.phase4DecisionFile = fullfile(rootDir, 'outputs', ...
    'v8_0_phase4_identifiability_pruning', ...
    'AS006_v8_0_phase4_pruning_decisions.csv');

cfg.outputDir = fullfile(rootDir, 'outputs', 'v8_0_phase5_transfer_plan');
cfg.manifestFile = fullfile(cfg.outputDir, 'RUN_MANIFEST.json');
cfg.candidateSetFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_transfer_candidate_set.csv');
cfg.devicePlanFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_device_plan.csv');
cfg.validationGateFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_validation_gates.csv');

cfg.transferPrimary = [ ...
    "combined physical bottleneck"; ...
    "contact-relaxed weak links"; ...
    "crack/tunnel-like weak links" ...
    ];
cfg.requiredControls = [ ...
    "no weak links"; ...
    "uniform weak links"; ...
    "shuffled weak links"; ...
    "central-lane / 1D-like" ...
    ];
cfg.diagnosticControls = [ ...
    "anisotropic control" ...
    ];
cfg.diagnosticHold = [ ...
    "boundary/SNS-inspired constriction" ...
    ];

cfg.devices = ["AS001"; "AS002"; "AS003"; "AS004"; "AS005"; "AS006"];
cfg.trainingAnchorDevice = "AS006";
cfg.validationMode = "six_device_transfer_with_leave_one_device_out";

end
