function cfg = phase5_config(rootDir)
%PHASE5_CONFIG Configuration for the reduced six-device transfer plan.

if nargin < 1 || isempty(rootDir)
    rootDir = fileparts(fileparts(mfilename('fullpath')));
end

repoRoot = fileparts(rootDir);

cfg = struct();
cfg.modelVersion = 'v8.0-phase5';
cfg.device = 'AS006';
cfg.repoRoot = repoRoot;
cfg.rootDir = rootDir;

cfg.phase4DecisionFile = fullfile(rootDir, 'outputs', ...
    'v8_0_phase4_identifiability_pruning', ...
    'AS006_v8_0_phase4_pruning_decisions.csv');

cfg.outputDir = fullfile(rootDir, 'outputs', 'v8_0_phase5_transfer_plan');
cfg.ledgerDir = fullfile(cfg.outputDir, 'device_ledgers');
cfg.manifestFile = fullfile(cfg.outputDir, 'RUN_MANIFEST.json');
cfg.candidateSetFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_transfer_candidate_set.csv');
cfg.devicePlanFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_device_plan.csv');
cfg.validationGateFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_validation_gates.csv');
cfg.dataManifestFile = fullfile(cfg.outputDir, 'phase5_data_manifest.csv');
cfg.transferScoreFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_transfer_scores.csv');
cfg.deviceSummaryFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_device_summary.csv');
cfg.leaveOneOutFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_leave_one_device_out.csv');
cfg.gateResultFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_gate_results.csv');
cfg.runStatusFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_device_run_status.csv');
cfg.figureBaseFile = fullfile(cfg.outputDir, ...
    'AS006_v8_0_phase5_transfer_summary');

cfg.phase4MechanismSummaryFile = fullfile(rootDir, 'outputs', ...
    'v8_0_phase4_identifiability_pruning', ...
    'AS006_v8_0_phase4_mechanism_identifiability.csv');
cfg.phase4CandidateScoreFile = fullfile(rootDir, 'outputs', ...
    'v8_0_phase4_identifiability_pruning', ...
    'AS006_v8_0_phase4_candidate_scores.csv');

cfg.transferPrimary = [ ...
    "combined physical bottleneck"; ...
    "contact-relaxed weak links"; ...
    "crack/tunnel-like weak links" ...
    ];
cfg.requiredControls = [ ...
    "no weak links"; ...
    "uniform weak links"; ...
    "shuffled weak links"; ...
    "central-lane / 1D-like" ...
    ];
cfg.diagnosticControls = [ ...
    "anisotropic control" ...
    ];
cfg.diagnosticHold = [ ...
    "boundary/SNS-inspired constriction" ...
    ];

cfg.devices = ["AS001"; "AS002"; "AS003"; "AS004"; "AS005"; "AS006"];
cfg.trainingAnchorDevice = "AS006";
cfg.validationMode = "six_device_transfer_with_leave_one_device_out";

cfg.runDeviceSweeps = false;
cfg.allowCachedAnchorEvidence = true;
cfg.requiredEvidenceDeviceFraction = 0.80;
cfg.levelA.enabled = true;
cfg.levelA.description = 'R(T) transfer across all six devices';
cfg.observableWeights.rtCurve = 0.45;
cfg.observableWeights.transitionMetrics = 0.25;
cfg.observableWeights.probe = 0.15;
cfg.observableWeights.nonlinear = 0.15;
cfg.sourceVersion = 'v7.4.6';
cfg.sourceScript = fullfile(repoRoot, 'matlab_v7_4_6_files', ...
    'run_v746_as006_gap_weaklink_sweep.m');
cfg.sourceOutputBase = fullfile(repoRoot, 'matlab_v7_4_6_files', 'outputs');
cfg.transferTopologyFilter = [ ...
    "combined"; ...
    "contact_relaxation"; ...
    "tear_lane"; ...
    "none"; ...
    "uniform"; ...
    "shuffled"; ...
    "central_lane" ...
    ];
cfg.alphaGapValues = [3.3 3.7 4.1];
cfg.gammaWValues = [0.05 0.10 0.20 0.40 0.70];
cfg.pWValues = [0.05 0.10 0.20 0.30];
cfg.runFullFieldMaps = false;
cfg.reuseExistingScreeningTables = false;

cfg.phase5A.enabled = true;
cfg.phase5A.description = 'Frozen-basin primary R(T) transfer across AS001-AS006';
cfg.phase5A.rtManifestFile = fullfile(cfg.outputDir, 'phase5_rt_manifest.csv');
cfg.phase5A.frozenBasinFile = fullfile(cfg.outputDir, ...
    'phase5_frozen_basin_set.csv');
cfg.phase5A.frozenTransferLedgerFile = fullfile(cfg.outputDir, ...
    'phase5_frozen_transfer_ledger.csv');
cfg.phase5A.summaryFile = fullfile(cfg.outputDir, ...
    'phase5_levelA_device_summary.csv');
cfg.phase5A.leaveOneOutFile = fullfile(cfg.outputDir, ...
    'phase5_levelA_leave_one_device_out.csv');
cfg.phase5A.gateResultFile = fullfile(cfg.outputDir, ...
    'phase5_levelA_gate_results.csv');
cfg.phase5A.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase5_levelA_rt_transfer_summary');
cfg.phase5A.parameterBasinScoreTolerance = 0.02;
cfg.phase5A.maxBasinRowsPerTrack = 10;
cfg.phase5A.commonSeeds = 101:110;
cfg.phase5A.maxTemperaturePoints = 120;
cfg.phase5A.Iprobe_A = 1e-8;
cfg.phase5A.score.rtScoreGridPoints = 160;
cfg.phase5A.score.weightCurve = 0.50;
cfg.phase5A.score.weightOnset = 0.20;
cfg.phase5A.score.weightWidth = 0.15;
cfg.phase5A.score.weightLowT = 0.15;
cfg.phase5A.score.onsetScale_K = 0.35;
cfg.phase5A.score.widthScale_K = 0.35;

cfg.phase5B.enabled = true;
cfg.phase5B.description = 'Held-out secondary-probe and hierarchical transfer validation';
cfg.phase5B.freezeManifestFile = fullfile(cfg.outputDir, ...
    'phase5B_frozen_phase5A_archive.csv');
cfg.phase5B.secondaryManifestFile = fullfile(cfg.outputDir, ...
    'phase5B_secondary_probe_manifest.csv');
cfg.phase5B.secondaryLedgerFile = fullfile(cfg.outputDir, ...
    'phase5B_secondary_probe_ledger.csv');
cfg.phase5B.deviceEvidenceFile = fullfile(cfg.outputDir, ...
    'phase5B_device_evidence_table.csv');
cfg.phase5B.classHeldoutFile = fullfile(cfg.outputDir, ...
    'phase5B_class_heldout_validation.csv');
cfg.phase5B.activationPlanFile = fullfile(cfg.outputDir, ...
    'phase5B_activation_law_plan.csv');
cfg.phase5B.gateResultFile = fullfile(cfg.outputDir, ...
    'phase5B_hierarchical_gate_results.csv');
cfg.phase5B.figureBaseFile = fullfile(cfg.outputDir, ...
    'phase5B_secondary_hierarchy_summary');
cfg.phase5B.maxTemperaturePoints = 120;
cfg.phase5B.Iprobe_A = cfg.phase5A.Iprobe_A;
cfg.phase5B.secondaryWeight = 0.55;
cfg.phase5B.asymmetryWeight = 0.45;
cfg.phase5B.complexityPenaltyLambda = 0.01;
cfg.phase5B.asymmetryOrderingTolerance = 0.08;
cfg.phase5B.asymmetryOnsetThreshold = 0.08;
cfg.phase5B.halfEncapsulatedDevices = ["AS002"; "AS004"; "AS006"];
cfg.phase5B.controlDevices = ["AS001"; "AS003"];
cfg.phase5B.crackDevices = "AS005";
cfg.phase5B.structuredRegimeDevices = ["AS004"; "AS005"; "AS006"];

end
