function summary = summarize_physics_case_sweep(caseTable)
%SUMMARIZE_PHYSICS_CASE_SWEEP Best case and deltas relative to baseline.

devices = unique(string(caseTable.device), 'stable');
rows = {};

for d = 1:numel(devices)
    device = devices(d);
    T = caseTable(string(caseTable.device) == device, :);
    Tscore = sortrows(T, 'combinedScore');
    best = Tscore(1,:);
    baseline = T(string(T.caseID) == "baseline_smooth", :);
    if isempty(baseline)
        baseline = best;
    else
        baseline = baseline(1,:);
    end

    rows(end+1,:) = {char(device), char(best.caseID), char(best.caseLabel), ...
        baseline.combinedScore, best.combinedScore, ...
        best.combinedScore - baseline.combinedScore, ...
        baseline.topPairScore, best.topPairScore, ...
        baseline.bottomPairScore, best.bottomPairScore, ...
        baseline.model_rLow, best.model_rLow, best.exp_rLow, ...
        baseline.sourceDrainPercOnset_K, best.sourceDrainPercOnset_K, ...
        best.domainLinkFraction, best.contactLinkFraction}; %#ok<AGROW>
end

summary = cell2table(rows, 'VariableNames', { ...
    'device','best_caseID','best_caseLabel','baseline_score','best_score', ...
    'delta_best_minus_baseline', ...
    'baseline_topPairScore','best_topPairScore', ...
    'baseline_bottomPairScore','best_bottomPairScore', ...
    'baseline_model_rLow','best_model_rLow','exp_rLow', ...
    'baseline_sourceDrainPercOnset_K','best_sourceDrainPercOnset_K', ...
    'best_domainLinkFraction','best_contactLinkFraction'});

end
